### ISSUE TITLE
Tablet caroussel thingy doesn't work

### ISSUE THREAD

**Issue by CubeFun** [ftde0/yt2009#101]
![nexusae0_Screenshot_2012-12-10-21-12-391](https://github.com/ftde0/yt2009/assets/109980144/5dde2221-b234-4b42-84cd-24d0ed403353)
By that i mean this, it just crashes the app but if you manage to click on browse fast enough everything else works

**Comment by ftde0** [comment]
what app version are you using? some apps like to crash for no apparent reason (for example 4.1.23 can crash if you scroll too fast).

also if the carousel doesn't show but the app is still open, make sure your setup supports hardware acceleration.

**Comment by mrkrabs206** [comment]
@CubeFun you did use 3.5.5 right?
