### ISSUE TITLE
Searching broken for custom client (should be an easy fix)

### ISSUE THREAD

**Issue by ListLostLisp** [ftde0/yt2009#104]
I am using an old app that should work with this service, but it is using a different way to search.

it searches for    /feeds/api/videos?vq=test&start-index=1&max-results=10
The v in ?vq breaks the searching. I was able to setup a crude proxy to edit the html on the fly to remove the v and after a few attempts I was able to view results on the app (my proxy was very slow for some reason and it kept timing out.)

I'm sorry I can't really read code so I was unable to find where I could add this. If you don't want to add this to the repo could you atleast guide me where to look? 

Here is some proof that it's not a mistake on the apps end.
https://web.archive.org/web/20100208214639/http://code.google.com/apis/youtube/migration.html

**Comment by gohoski** [comment]
This not only affects this custom client, but also the 1.4.20 (and possibly earlier) versions of the official YouTube app (although with `/proxy` added before the endpoint):
```java
mFeedMap.put(YouTubeUrlType.SEARCH, new FeedInfo(appendCountryRestriction("proxy/feeds/api/videos?vq=%1$s&format=2")));
```
(code from a decompiled APK)

**Comment by mrkrabs206** [comment]
> I am using an old app that should work with this service, but it is using a different way to search.
> 
> it searches for /feeds/api/videos?vq=test&start-index=1&max-results=10 The v in ?vq breaks the searching. I was able to setup a crude proxy to edit the html on the fly to remove the v and after a few attempts I was able to view results on the app (my proxy was very slow for some reason and it kept timing out.)
> 
> I'm sorry I can't really read code so I was unable to find where I could add this. If you don't want to add this to the repo could you atleast guide me where to look?
> 
> Here is some proof that it's not a mistake on the apps end. https://web.archive.org/web/20100208214639/http://code.google.com/apis/youtube/migration.html

Can you give us a photo

**Comment by ListLostLisp** [comment]
I changed all mentions of "req.query.q" in yt2009 to "req.query.vq" and that fixed it. 
The app now shows results but doesn't seem to parse the xml correctly to load the video links, but that's a different issue.
