### ISSUE TITLE
cmd says illegal option when doing docker method

### ISSUE THREAD

**Issue by nope312** [ftde0/yt2009#11]
after i do docker run -it -p 8080:80 yt2009, it says " docker-entrypoint.sh: set: line 2: illegal option - "

**Comment by breakgimme** [comment]
sorry for taking so long to respond
i'm unable to replicate the issue, even after pruning my docker environment
can you please provide some details about your system?
@TheOnlyOne12315 are you having the same issue?

**Comment by TheOnlyOne12315** [comment]
> sorry for taking so long to respond i'm unable to replicate the issue, even after pruning my docker environment can you please provide some details about your system? @TheOnlyOne12315 are you having the same issue?

No, But it's an illegal option !1!111 (I'm joking)
