### ISSUE TITLE
API Key issues

### ISSUE THREAD

**Issue by FurblandChannel** [ftde0/yt2009#111]
Long story short, I’m trying to patch the Ask.com YouTube toolbar widget to work with YT2009. Only issue is, it tries to fetch data from /api/standardfeeds, which appears to return nothing. I’ve tried swapping that out with a playlist URL, but it always appends ?key=(some api key) to the very end of the URL. For whatever reason, when ?key (or any other random parameter) is appended to the URL it returns 500. This is an issue, because anything that tries to specify an API key (so basically every janky 3rd party app) is completely nonfunctional even if being correctly patched.

**Comment by ftde0** [comment]
yt2009's gdata v2 endpoints do not check or use any keys. the issue most likely is within something else within the requests sent (unimplemented params? something overall breaking?).

**Comment by FurblandChannel** [comment]
It seems to be the unrecognized parameter that is crashing it (any unrecognized parameter does the same). Perhaps it should ignore these?

**Comment by ftde0** [comment]
no response in a while, assuming it's solved? feel free to reopen/create a new issue if still happening
