### ISSUE TITLE
Weird problem

### ISSUE THREAD

**Issue by CubeFun** [ftde0/yt2009#115]
Hi, i have a question about yt2009. So in /mobile/blzr i noticed when i use it on my 3ds i saw when you go load a video it says that it wasnt able to load the video, i eventually figured out why, its because when the video loads on the 3ds it doesnt load it from http://192.168.240.30/assets/videoid.mp4 but from http://192.168.240.30/get_video?video_id=videoid/mp4, this page is supposed to redirect you straight to the mp4 file but on my 3ds it doesnt for some reason, so im wondering if there is any way if you click on a video to redirect it straight to the mp4 file instad from http://192.168.240.30/get_video?video_id=videoid/mp4 to http://192.168.240.30/assets/videoid.mp4

**Comment by ftde0** [comment]
`/get_video?video_id=[id]/mp4` urls that end up redirecting you to the mp4 itself do have their use - it makes sure the video is downloaded first before sending (and will download it if it isn't), so you'd most likely end up with most videos not playing if you omitted get_video.

i'll try to have a look at this though.

**Comment by CubeFun** [comment]
Hmm, okay . Is there a way it can send a fetch request when you straight open the video even if its not downloaded? Or download the video if the url of the video is opened but you do not play the video?

**Comment by CubeFun** [comment]
> `/get_video?video_id=[id]/mp4` urls that end up redirecting you to the mp4 itself do have their use - it makes sure the video is downloaded first before sending (and will download it if it isn't), so you'd most likely end up with most videos not playing if you omitted get_video.
> 
> i'll try to have a look at this though.

Hey btw i have another question, is there a way to patch the early 2005 player, so far i have been able to patch the mid 2005 player but no luck with early 2005 so far
