### ISSUE TITLE
A suggestion for YT2009: YouTube TV

### ISSUE THREAD

**Issue by gigigigi53** [ftde0/yt2009#116]
Since there's only YouTube XL (which somehow looks like YouTube TV), I would also want this as well.
It's like this:
![Submit to r_oldyoutubelayout - Google Chrome 2024-08-09 00_37_44](https://github.com/user-attachments/assets/d3b6049e-3ebb-4529-94c6-5309c0dccfb4)
You would have to find the assets, the Flash SWFs and make the code work with YT2009 (local/hosted). Okay, please add this suggestion to YT2009, thank you.

**Comment by ftde0** [comment]
hello @mrkrabs206 / u/MildOff2024,
before we continue, i'd like to let you know that escaping to a different github account after being called out at #112 (and continuing the very actions you've been called out for!) will not be tolerated.

but, on a more positive note, after a very quick look, you can easily tell that the api used is similar (if not the same) as youtube xl. you should have next to no trouble adapting it to yt2009 and doing eventual troubleshooting. quite frankly, they're both very similarly made.
