### ISSUE TITLE
Having issue with annotations (and captions) on Flash video player

### ISSUE THREAD

**Issue by mrkrabs206** [ftde0/yt2009#122]
So when I patched early 2010 and late 2008, I also did make the captions and annotations to work with it. Also patched iv_module with my own instance and it's done.
On the early 2010 one, only the captions work and no annotations (https://ibb.co/kK5jWJZ https://ibb.co/JyRgHgZ)
On late 2008, none of them work (https://ibb.co/mbzY2KM https://ibb.co/51T2Nnr)
Also captions doesn't work in the watch video in a new window (early 2010)
Any fix or help is appreciated. Thank you

**Comment by ftde0** [comment]
watch in a new window hasn't been updated in a while and basically only sends the data necessary to play the video (so no captions etc). thanks for reminding me that this function exists.

also, the video you're testing for early 2010 doesn't seem to have annotations at all. test with something which is sure to have them, like https://www.youtube.com/watch?v=kLDUnUtRiHM.

been a while since i touched those 2 functions for as2 players (so anything before the late 2010), but in as3 players (late2010 and later) the modules have to match the exact version of the player you're using, otherwise most likely you're ending up in a crash.

**Comment by mrkrabs206** [comment]
> watch in a new window hasn't been updated in a while and basically only sends the data necessary to play the video (so no captions etc). thanks for reminding me that this function exists.
> 
> also, the video you're testing for early 2010 doesn't seem to have annotations at all. test with something which is sure to have them, like https://www.youtube.com/watch?v=kLDUnUtRiHM.
> 
> been a while since i touched those 2 functions for as2 players (so anything before the late 2010), but in as3 players (late2010 and later) the modules have to match the exact version of the player you're using, otherwise most likely you're ending up in a crash.

Unfortunately not available either

**Comment by mrkrabs206** [comment]
I patched iv module and e2010 player correctly

**Comment by ftde0** [comment]
can you send your player and iv_module swfs where you're having issues?

**Comment by gigigigi53** [comment]
> can you send your player and iv_module swfs where you're having issues?

[dsfd.zip](https://github.com/user-attachments/files/16644663/dsfd.zip)

**Comment by gigigigi53** [comment]
here @ftde0 my player and iv module

**Comment by ftde0** [comment]
looks like we're both at fault here.

on your end, looks like you forgot slashes at the end of base_url for iv_module. also, `https` doesn't work very well with IPs, so just to be on the safe side, set the other one to `http`.
![192](https://github.com/user-attachments/assets/b4c26ffa-70f9-468e-b102-616fd5e50aef)
your resulting value should be `http://192.168.0.192/`.

on my end, looks like the alt iv_module doesn't correctly attach. for the time being, you can work around this by putting the path to your iv_module in your video_id argument on /toggle_f, like so:
`iv_module=http://192.168.1.7/media/tswf/iv_module.swf&video_id`
just replace the full path to your module in the text above.

**Comment by gigigigi53** [comment]
> looks like we're both at fault here.
> 
> on your end, looks like you forgot slashes at the end of base_url for iv_module. also, `https` doesn't work very well with IPs, so just to be on the safe side, set the other one to `http`. ![192](https://private-user-images.githubusercontent.com/76792259/358856288-b4c26ffa-70f9-468e-b102-616fd5e50aef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MTQ1MjIsIm5iZiI6MTcyMzkxNDIyMiwicGF0aCI6Ii83Njc5MjI1OS8zNTg4NTYyODgtYjRjMjZmZmEtNzBmOS00NjhlLWIxMDItNjE2ZmQ1ZTUwYWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDE3MDM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMTdhMjRkZTUzZGM1MDBiOWUzMjljMWMzYjkwMDIxZDc5NTZhMzc4NjY2ZDM2NTM0MzgxMTg5YzI5OTZjNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9guOHVfAFIchWPOJ7RRRsT-CQRva382-qfOV0995qIw) your resulting value should be `http://192.168.0.192/`.
> 
> on my end, looks like the alt iv_module doesn't correctly attach. for the time being, you can work around this by putting the path to your iv_module in your video_id argument on /toggle_f, like so: `iv_module=http://192.168.1.7/media/tswf/iv_module.swf&video_id` just replace the full path to your module in the text above.

Here:
![JPEXS Free Flash Decompiler v 15 1 1 - C__Users_Z_Downloads_yt2009-main_yt2009-main_iv_module swf 2024-08-17 20_06_16](https://github.com/user-attachments/assets/c7252ac2-072d-4dc0-8bae-84503707af08)

Now annotations work. Here's one on late 2008:
![YouTube - Annoying Annotations - Pale Moon 2024-08-17 20_07_45](https://github.com/user-attachments/assets/b48d5e4e-206a-42c8-a84a-638a07728316)
![YouTube - Annoying Annotations - Pale Moon 2024-08-17 20_07_40](https://github.com/user-attachments/assets/784335c4-0be1-4793-a763-0e0c05df1e86)

**Comment by gigigigi53** [comment]
So, will this remain until a fix is found or it will be as it be?
Also I want to patch annotations and captions on late 2011 player.

**Comment by gigigigi53** [comment]
Oh and I'm leaving this open if something goes wrong with this. (captions or annotations and patching players).

**Comment by gigigigi53** [comment]
Buuut..... @ftde0 captions doesn't work YET. The code was changed, but we would have to add this (subtitle_module=http://192.168.0.192/subtitle_module.swf&video_id) to make it work. It recognizes it to turn on captions but it says not available.

**Comment by gigigigi53** [comment]
Okay so I renamed subtitle-module to subtitle_module and now captions work as well.
Here:
![Basilisk (Private Browsing) 2024-08-17 20_48_49](https://github.com/user-attachments/assets/023bcbcb-c7a4-41be-81ca-f35d7b8ac08c)
![Basilisk (Private Browsing) 2024-08-17 20_48_44](https://github.com/user-attachments/assets/373ab393-1dfb-464a-8f44-2a68e08ff075)
Here is also colored:
![Basilisk (Private Browsing) 2024-08-17 20_51_39](https://github.com/user-attachments/assets/31f9ec5d-6b01-451d-867d-5832a4aa214a)

**Comment by ftde0** [comment]
glad you got everything working! i'll see what can be done in the future to make it easier in such cases.

**Comment by mrkrabs206** [comment]
> glad you got everything working! i'll see what can be done in the future to make it easier in such cases.

Okay cool!

**Comment by mrkrabs206** [comment]
Also I have 4 questions:
1. Can you do like a tutorial for patching 1.x YouTube apps? (no begs, it's been 6 months)
2. Next to 1.x app patching, please have mobile captions support (next to Flash and HTML5 web players).
3. I know that's stupid, but you should have a fix for HQ toggle (1.3-4.3.9).
4. If you know that I have a question, you should make a escargot.chat account for PMming you about YT2009 issues and suggestions! User will be ftde0@escargot.chat.
Thanks @ftde0 if you read this.
