### ISSUE TITLE
A suggestion for YT2009: Ad module and ads on web and mobile (Flash and HTML5 including on apps excluding web mobile)

### ISSUE THREAD

**Issue by gigigigi53** [ftde0/yt2009#123]
Well, since YT2009 has been ad-free lately, and emulating ads in flags was a thing until it went away. Now this suggestion might be crazy, but it's just for tests and "flexing". The ads will be from the USA from 2009-march 2010. Anyway, it might be or not be in the future. Thank you.

**Comment by userunknown358** [comment]
No.
