### ISSUE TITLE
How do I patch AS3 players (late 2010-mid 2015) players to support annotations and captions?

### ISSUE THREAD

**Issue by gigigigi53** [ftde0/yt2009#126]
Next to AS2 players (late 2008-mid 2010) along with late 2010 and mid 2012, I also want to patch the others for both annotations and captions. There aren't any links that I can work with, so please give me something to help me with.
Additionaly, I'm stuck on 360p on mid 2008-mid 2010/early 2011-mid 2015 players. How do I fix that to get HQ/480p and HD/720p-1080p? Thank you!

**Comment by gigigigi53** [comment]
I found out inside the code there are ccmodule and subtitle module (&cc_module=http%3A%2F%2F192.168.0.192%3A80%2Fsubtitle-module.swf&cc_load_policy=2&iv_load_policy=2&enablejsapi=1&cc3_module=http%3A%2F%2F192.168.0.192%3A80%2Falt-swf%2Fmodules%2F2010_subtitles3_module-vfl183159.swf&iv3_module=http%3A%2F%2F192.168.0.192%3A80%2Falt-swf%2Fmodules%2F2010_iv3_module-vfl183159.swf&endscreen_module=http%3A%2F%2F192.168.0.192%3A80%2Falt-swf%2Fmodules%2F2010_endscreen-vfl183159.swf for 2010 and &cc_module=http%3A%2F%2F192.168.0.192%3A80%2Fsubtitle-module.swf&cc_load_policy=2&iv_load_policy=2&enablejsapi=1&cc3_module=http%3A%2F%2F192.168.0.192%3A80%2Falt-swf%2Fmodules%2F2012_subtitles3_module-vfl183159.swf&iv3_module=http%3A%2F%2F192.168.0.192%3A80%2Falt-swf%2Fmodules%2F2012_iv3_module-vfl183159.swf for 2012)

**Comment by gigigigi53** [comment]
@ftde0 If you are reading this, Please have a fix for this as it's not working on other players
![Pale Moon (Private Browsing) 2024-08-24 22_38_27](https://github.com/user-attachments/assets/2ebc873e-9d30-49a8-9b2e-8d04efe624e5)
![Pale Moon (Private Browsing) 2024-08-24 22_39_08](https://github.com/user-attachments/assets/448b5d75-079a-4782-8adb-5665541ecd50)
(annotations)
![Pale Moon (Private Browsing) 2024-08-24 22_40_02](https://github.com/user-attachments/assets/440df7fa-2c18-4588-8984-5c295a2449e4)
![Pale Moon (Private Browsing) 2024-08-24 22_40_05](https://github.com/user-attachments/assets/7924440a-3d50-4f3e-a3ea-647648a3340b)
(captions)

**Comment by gigigigi53** [comment]
Btw, embedded players (2014 and 2015) do not have that lol

**Comment by breakgimme** [comment]
can't you read?

> the modules have to match the exact version of the player you're using, otherwise most likely you're ending up in a crash.

https://github.com/ftde0/yt2009/issues/122#issuecomment-2294358468

**Comment by gigigigi53** [comment]
> can't you read?
> 
> > the modules have to match the exact version of the player you're using, otherwise most likely you're ending up in a crash.
> 
> [#122 (comment)](https://github.com/ftde0/yt2009/issues/122#issuecomment-2294358468)

I am sorry I really want help with it

**Comment by gigigigi53** [comment]
ignore this @ftde0 breakgimme said cant you read. i am reading lol

**Comment by ftde0** [comment]
i am afraid you are - in fact - not reading.

**Comment by gigigigi53** [comment]
> i am afraid you are - in fact - not reading.

and i am sorry

**Comment by gigigigi53** [comment]
don't block me but anyways where can i get each as3 iv module and subtitle module (along with endscreen) to make it work with other players?
