### ISSUE TITLE
The theater mode button (expand/shrink) does nothing on early 2010-early 2013 players (YT2009 player size doesn't change)

### ISSUE THREAD

**Issue by gigigigi53** [ftde0/yt2009#128]
[I am excluding mid-late 2013, 2014 and 2015 players since they are embedded :(]
I don't know why, but the players won't expand or shrink its size.

On early 2010, nothing happens when I click on it (unless changing its size manually):

https://github.com/user-attachments/assets/12bf4d32-d2e4-4e19-a95f-1326d9dffa0a

Also applies to mid 2010

On late 2010 to early 2013, the button works, but YT2009 isn't changing its size.
Here's one on late 2011:

https://github.com/user-attachments/assets/5b8e3eae-c48e-4a2a-b116-b5b608a775be

(also applies to late 2010/early 2012-early 2013)

@ftde0, if you read this, the problem needs to be fixed by editing some code inside f_mode related to changing player size/theater mode.

Anyway, thank you.

**Comment by ftde0** [comment]
those players were made for different layouts, obviously they won't work with 2009 layout just like that. not a high priority.

**Comment by gigigigi53** [comment]
> those players were made for different layouts, obviously they won't work with 2009 layout just like that. not a high priority.

Would need a fix!
