### ISSUE TITLE
annotations wont show up under flash player

### ISSUE THREAD

**Issue by jackhacksren** [ftde0/yt2009#13]
in html5 it works but not in flash will you fix it in the future hmm

**Comment by ftde0** [comment]
flash annotations are very picky and can be made to work, make sure you've changed both the urls in both the player and the iv_module.

if you have a semi-modern browser with flash, you can use the Network tab in devtools to see what's going wrong and fix accordingly

**Comment by jackhacksren** [comment]
i wonder where the iv_module is located

**Comment by ftde0** [comment]
kinda buried but it's in the main dir (with all the base html files, /watch.swf and such)

**Comment by jackhacksren** [comment]
i tried patching the iv_module replacing ur ip with my localhost which is 127.0.0.1 and allowing the security to let my localhost still doesnt show annotations i also dont know how to see whats going wrong in the network tab

**Comment by ftde0** [comment]
![Untitled](https://github.com/ftde0/yt2009/assets/76792259/aa4954d6-e7b2-407f-8f3f-903c7bf293b2)

you're looking for:
- iv_module being requested from the right source (click on a request to make sure it's going to the right domain and such)
- crossdomain.xml doesn't restrict the connection
- read2 is sent (this is the request for actual annotations themselves, once this is done the annotations should show up)

also make sure you're using the http url.

**Comment by jackhacksren** [comment]
crossed out the crossdomain.xml 
i dont see iv_module in the network tabs or read2

**Comment by ftde0** [comment]
assuming you're using and modifying the default player (/watch.swf), search it up in the decompiler for "iv_module" and check if there is no hardcoded url to the module. if so put your iv_module url in there.

**Comment by jackhacksren** [comment]
trying to use the default swf it only says error has occured when trying to patch it and allowing it

**Comment by ftde0** [comment]
iv_module doesn't seem to work on other players. make sure you've patched the player correctly. if in doubt always check the network tab and solve the issues from there.

in the network tab for the default player you're looking for whether the /get_video request is made. perhaps you've entered the base url incorrectly?

**Comment by jackhacksren** [comment]
i did not type the ip wrong i typed the ip at live base url and at the security my browser is chrome 41 and npapi flash 32.0.0.371 with playerglobal swc of 30.0 with the right jpex version 15.1.1

i hope this information helps

**Comment by jackhacksren** [comment]
> i tried patching the iv_module replacing ur ip with my localhost which is 127.0.0.1 and allowing the security to let my localhost still doesnt show annotations i also dont know how to see whats going wrong in the network tab

even trying to change my hosting ip to that of the already put in one 192.168.1.4 it wont work

**Comment by ftde0** [comment]
you didn't seem to give back any info about this part
> if in doubt always check the network tab and solve the issues from there.

if all else fails, try pulling the 2009 player yourself from an archived 2009 watchpage and try patching that.

take a 2009 archive like http://web.archive.org/web/20091101160503/https://www.youtube.com/watch?v=jNQXAC9IVRw, view its source (ctrl+u) and look for `.swf`. this should bring up a few results, but what you're looking for is one of the `watch-vfl[...].swf` files. copy its url, download and try patching those.

**Comment by jackhacksren** [comment]
> you didn't seem to give back any info about this part
> 
> > if in doubt always check the network tab and solve the issues from there.
>

i have no idea how do i even see what is wrong from there i on see the module or read2

but im gonna try the 2009 archive

**Comment by jackhacksren** [comment]
> but im gonna try the 2009 archive

the archived one worked

annotations still arent coming in even if the iv_module it self is patched

**Comment by ftde0** [comment]
the archive i sent also has an iv_module so you could try patching that one so they matched

**Comment by jackhacksren** [comment]
even patching that 2009 iv module did not work i also patched the player to include the iv module still didnt work

no idea why

**Comment by jackhacksren** [comment]
im also using the DEV enviroment thingy if that helps

**Comment by jackhacksren** [comment]
> ![Untitled](https://private-user-images.githubusercontent.com/76792259/284076002-aa4954d6-e7b2-407f-8f3f-903c7bf293b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMjU3OTksIm5iZiI6MTcwMjIyNTQ5OSwicGF0aCI6Ii83Njc5MjI1OS8yODQwNzYwMDItYWE0OTU0ZDYtZTdiMi00MDdmLThmM2YtOTAzYzdiZjI5M2IyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDE2MjQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5MmUzNmQ1NTQ3YjRlODY3YzczYmY1NjFkNjFhZjY4YmEyMGFhY2U4YTA2YjAzMDMwNDBhZjM0M2NlNGQyZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ABtXVbf3sanMwiB0EqnyQNqqZFKQNWEkRYxelIB9idM)
> 
> you're looking for:
> 
> * iv_module being requested from the right source (click on a request to make sure it's going to the right domain and such)
> * crossdomain.xml doesn't restrict the connection
> * read2 is sent (this is the request for actual annotations themselves, once this is done the annotations should show up)
> 
> also make sure you're using the http url.

btw what browser is this on that screenshot

**Comment by ftde0** [comment]
not sure if you're still dealing with the issue and tbh your comment reminded me of that issue in the first place.

the browser is basilisk. it's based on older firefox, so i wouldn't use it for anything other than flash content. but for flash it works nicely.

regarding the original issue, i kinda mentioned a fair way to find what's causing a flash player to not work (you could use some of the steps in your annotations case) [here.](https://github.com/ftde0/yt2009/issues/23)

**Comment by jackhacksren** [comment]
i dont see a green read2 at all crossdomain is allowing the connection too

**Comment by ftde0** [comment]
feel free, i could have a look when i have free time

**Comment by jackhacksren** [comment]
[watch-vfl129881.zip](https://github.com/ftde0/yt2009/files/13686892/watch-vfl129881.zip)

i should also note that iv_module is located in yt2009 while the player is located at alt-swf

**Comment by ftde0** [comment]
the watch player is in alt-swf right?

what if you move it to yt2009 and rename it to `watch.swf`?

**Comment by jackhacksren** [comment]
> the watch player is in alt-swf right?
> 
> what if you move it to yt2009 and rename it to `watch.swf`?

annotations didnt appear but the HQ button did appear

**Comment by ftde0** [comment]
move your iv_module back to yt2009. make sure its name is `iv_module.swf` with nothing else in its name.

**Comment by jackhacksren** [comment]
> Reference in new

i already did that and its already that name

**Comment by jackhacksren** [comment]
> move your iv_module back to yt2009. make sure its name is `iv_module.swf` with nothing else in its name.

i already did that and its already that name

**Comment by ftde0** [comment]
had a closer look at your iv_module and compared it against mine. change the `DEFAULT_STORAGE_SERVER_BASE_URL` from `"http://www.google.com/reviews/y/"`. to your base url. in your case it would be `"http://127.0.0.1/"`.

the base_url is located in `google/youtube/iv/common/Config`. or use the text search to find the url.

**Comment by jackhacksren** [comment]
> had a closer look at your iv_module and compared it against mine. change the `DEFAULT_STORAGE_SERVER_BASE_URL` from `"http://www.google.com/reviews/y/"`. to your base url. in your case it would be `"http://127.0.0.1/"`.
> 
> the base_url is located in `google/youtube/iv/common/Config`. or use the text search to find the url.

that still didnt work 

using annoying annotations as an test to see if annotations work appeared in html5 so should in flash too

**Comment by ftde0** [comment]
went on to troubleshoot with @fortisiontek to make annotations work on [yt2009.giabs.ovh](http://yt2009.giabs.ovh/). here's what we found.

assuming you've done everything else said before (set the iv_module paths, storage server base url etc)

both the flash player and the iv_module have url validators in them that check if everything is requested from a youtube domain. you will need to bypass the checks as shown below.
![bypass1](https://github.com/ftde0/yt2009/assets/76792259/f0778216-5f13-494a-a0f0-ba62b39aeb04)
![bypass2](https://github.com/ftde0/yt2009/assets/76792259/08590583-d760-4206-9d0b-3e207a622f2f)

you may need to set up a crossdomain correctly if you're using your yt2009 instance under a domain.
```
<cross-domain-policy>
    <allow-access-from domain="domain_name" secure="false"/>
    <allow-access-from domain="direct_ip" secure="false"/>
</cross-domain-policy>
```
even if you're using yt2009 from a direct ip, it won't hurt to have that correctly set up so you don't run into issues.

the iv_module swf is requested from the ip you've set up in back/config.json. make sure that is set correctly. you can check whether it is by viewing source (ctrl+u) on the watch page and searching `<embed`.
![embed](https://github.com/ftde0/yt2009/assets/76792259/16d83aaf-ba73-4540-b7b4-19bb837b6d5d)

also a way of knowing whether the iv_module loads is by the annotation icon.

iv_module not loaded:
![iv_not_loaded](https://github.com/ftde0/yt2009/assets/76792259/2fe20d0b-2a2c-4f8d-b456-7feed4287946)

iv_module loaded, can't load annotations themselves:
![iv_loaded](https://github.com/ftde0/yt2009/assets/76792259/204c3e23-3166-4fd9-a407-60e3cc16cd7c)

**make sure your ip from config.json matches the one you're using and the one you've set while patching the players and their paths.**

**Comment by jackhacksren** [comment]
> went on to troubleshoot with @fortisiontek to make annotations work on [yt2009.giabs.ovh](http://yt2009.giabs.ovh/). here's what we found.
> 
> assuming you've done everything else said before (set the iv_module paths, storage server base url etc)


in addition i added my ip to the youtube domains and the storange domain whitelist  and allowed security domains 

i also have no idea on what ur trying to say on the iv module part do i delete return true and }

**Comment by jackhacksren** [comment]
now it has the red ! but when i try to turn it on it says it isnt available

when i try to search read2 and noticed that 127.0.0.1read2 i put 127.0.0.1/read2 instead and it wont actually turn on even if i click turn on annotations 


another thing i encounter is 

Error: ENOENT: no such file or directory, open 'C:\Users\jacke\Desktop\yt2009\yt2009\back\cache_dir\annotations\kLDUnUtRiHM\crossdomain.xml.xml'
    at Object.open (node:internal/fs/sync:78:18)
    at Object.openSync (node:fs:565:17)
    at Object.writeFileSync (node:fs:2288:35)
    at C:\Users\jacke\Desktop\yt2009\yt2009\back\cache_dir\annotations_cache_manager.js:21:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\jacke\\Desktop\\yt2009\\yt2009\\back\\cache_dir\\annotations\\kLDUnUtRiHM\\crossdomain.xml.xml'
}

**Comment by jackhacksren** [comment]
there is 2 file extensions but when i look at the file explorer it only has 1

**Comment by jackhacksren** [comment]
e

**Comment by ftde0** [comment]
let me be honest,
i don't know what you've done, how you managed to do it. i've never managed to trigger an error you sent and i don't know how one would do so.

you're probably on your own. i'd advise you to redownload the iv_module from the repo and start over.

**Comment by jackhacksren** [comment]
> let me be honest, i don't know what you've done, how you managed to do it. i've never managed to trigger an error you sent and i don't know how one would do so.
> 
> you're probably on your own. i'd advise you to redownload the iv_module from the repo and start over.

the annotations themselfs exist there is just xml.xml
