### ISSUE TITLE
I'm having an issue with AS3 iv3 and subtitles3 modules. Did I do everything right? How to fix?

### ISSUE THREAD

**Issue by gigigigi53** [ftde0/yt2009#131]
Hi, so I have a problem with the AS3 modules. On AS2 the iv and subtitle modules work fine (universally). Including end screen (no separate SWF).

But on AS3 (late 2010-early 2013), there are problems with it. On captions, when turned on, it just turns off back!

https://github.com/user-attachments/assets/89e3bf16-0660-481e-935c-bacf03622189

On annotations however, some of them turn on and other stay forever trying to turn on.

https://github.com/user-attachments/assets/f346d418-bdcf-4076-b307-b02301d554ba

![Pale Moon (Private Browsing) 2024-08-30 18_26_40](https://github.com/user-attachments/assets/f3e41f79-3400-4634-94b3-8d76b4a09199)
![Pale Moon (Private Browsing) 2024-08-30 18_26_45](https://github.com/user-attachments/assets/118ddabe-2462-4035-8207-092f75f4fcd7)

But end screens do work however, but related videos aren't visible (or maybe).
![Pale Moon (Private Browsing) 2024-08-30 18_21_54](https://github.com/user-attachments/assets/1ebf93d1-af22-422e-a221-c5270b6383e2)

Is there something I can fix to make this work flawlessly? This is late 2011, all of the SWFs are from Dec 2, 2011 at 8:36 PM (20:36). Thank you

**Comment by gigigigi53** [comment]
Even moving it to alt-swf just does nothing :-(

Help me @ftde0 if you're online

**Comment by gigigigi53** [comment]
Log from the Flash 34 debugger (annotations):
TypeError: Error #1009: Cannot access a property or method of a null object reference. videoId: kLDUnUtRiHM/mp4
	at com.google.youtube.modules.iv.model::OpenUrlAction/updateUrl()
	at com.google.youtube.modules.iv.model::OpenUrlAction$/fromXml()
	at com.google.youtube.modules.iv.model::ActionFactory$/fromXml()
	at com.google.youtube.modules.iv.model::Annotation$/fromXml()
	at com.google.youtube.modules.iv::IvModule/loadAnnotations()
	at com.google.youtube.modules.iv::IvModule/loadXml()
	at com.google.youtube.modules.iv::IvModule/onLoadComplete()
	at flash.events::EventDispatcher/dispatchEventFunction()
	at flash.events::EventDispatcher/dispatchEvent()
	at com.google.youtube.modules.iv::AnnotationsLoader/onLoadComplete()
	at flash.events::EventDispatcher/dispatchEventFunction()
	at flash.events::EventDispatcher/dispatchEvent()
	at flash.net::URLLoader/onComplete()

**Comment by gigigigi53** [comment]
HEEEEELOOOOO?????

**Comment by mrkrabs206** [comment]
> HEEEEELOOOOO?????

???????

**Comment by gigigigi53** [comment]
no response

**Comment by ftde0** [comment]
the void responded, your hello calls seemed to have went nowhere. wake up, you've been in a coma. flash players are calling, they need you to fix them...

**Comment by gigigigi53** [comment]
> the void responded, your hello calls seemed to have went nowhere. wake up, you've been in a coma. flash players are calling, they need you to fix them...

I am sorry, but i'm having a problem with the broken as3 modules.
There is no base url so I can't do anything to fix them yet...
