### ISSUE TITLE
2009 CPS (embed) Players searchbar doesnt work

### ISSUE THREAD

**Issue by CubeFun** [ftde0/yt2009#135]
Just as the title says, - https://youtu.be/_1NR70ZFd-Y heres a vid of it, this also happens on the 2008 one and also heres a link to the exact player used it the video - https://www.mediafire.com/file/yljf8g6ij6ikp3k/cps2009.swf/file (base url is 192.168.240.32)

**Comment by gigigigi53** [comment]
On 2008 one, related videos also aren't working.

**Comment by ftde0** [comment]
not sure if this is still needed, but for cpb/cps players, you also need to change the gdata urls - `gdata.youtube.com` - to your yt2009 host's ip.

this is mentioned in entries for those in alt-swf. https://github.com/ftde0/yt2009/blob/main/alt-swf/readme.md

**Comment by CubeFun** [comment]
> not sure if this is still needed, but for cpb/cps players, you also need to change the gdata urls - `gdata.youtube.com` - to your yt2009 host's ip.
> 
> this is mentioned in entries for those in alt-swf. https://github.com/ftde0/yt2009/blob/main/alt-swf/readme.md

Thanks, it really did help
