### ISSUE TITLE
Fixed post_config_setup.js to add 'magick' in convert.

### ISSUE THREAD

**Issue by gigigigi53** [ftde0/yt2009#138]
[post_config_setup.zip](https://github.com/user-attachments/files/17025369/post_config_setup.zip)
At least the ffmpeg will know that it's installed.

**Comment by breakgimme** [comment]
it's `convert` and not `magick convert` for a reason, see https://github.com/search?q=repo%3Aftde0%2Fyt2009%20convert&type=code
also you shouldn't use issues to request your changes to be merged, pull requests exist
