### ISSUE TITLE
Crash when accessing channels via mobile

### ISSUE THREAD

**Issue by starterbeeee** [ftde0/yt2009#14]
Trying to access a couple of channels via mobile (2.1.6-2106) ends up with this:
![error](https://github.com/ftde0/yt2009/assets/83183177/13d6e9aa-4fff-4606-afbc-085cc5dc1f3e)
Though, it works fine on web.
Did i do something wrong in my setup?

**Comment by ftde0** [comment]
you've done nothing wrong from what i can see and it's most likely an oversight on my side. an update is coming out this wednesday so i'll fix that and close the issue once done.

thanks for the report!

**Comment by ftde0** [comment]
forgot to close, implemented smth so it shouldn't crash
