### ISSUE TITLE
alter convert.exe to use imagemagick instead.

### ISSUE THREAD

**Issue by john123903** [ftde0/yt2009#140]
post_config_setup.js needs to update to use imagemagick instead of convert.

(if convert.exe is not imagemagick please provide me a url)

**Comment by TheBigFatOof** [comment]
ImageMagick removed convert.exe in the latest versions (despite still mentioning it in the installer where you select to install legacy components.)

You'll need to use an older version of ImageMagick. I'm pretty sure this is the last version to include convert.exe: https://web.archive.org/web/20240615174506if_/https://imagemagick.org/archive/binaries/ImageMagick-7.1.1-33-Q16-HDRI-x64-dll.exe

It may also be possible to take the convert.exe from that version and slip it back into the installation directory of the latest version, but I haven't tried it.

**Comment by ftde0** [comment]
will be taken into consideration within the next update. thanks for the report!

**Comment by john123903** [comment]
> will be taken into consideration within the next update. thanks for the report!

did you fix it now?

**Comment by ftde0** [comment]
addressed in https://github.com/ftde0/yt2009/commit/01e6edac8d11424c63faf0e9bd03c173a14d48f9
