### ISSUE TITLE
uhhhh... help?

### ISSUE THREAD

**Issue by Pwnz0rserver2009** [ftde0/yt2009#141]
while trying to write a 2011 layout for yt2009, i messed everything up and decided to just completely reinstall yt2009
problem is, whatever i messed up now causes this when i try to set up yt2009
![image](https://github.com/user-attachments/assets/6efe4719-2641-4ac8-b0bf-dfc79b000e96)
help?

**Comment by Pwnz0rserver2009** [comment]
by the way, it'd be nice to have a little more documentation.

**Comment by mrkrabs206** [comment]
It's incompatible with Windows XP Server 2003/R2, Vista, Server 2008/R2 7 (right now). Use Windows 8, Server 2012/R2, 8.1, 10, Server 2016

**Comment by Pwnz0rserver2009** [comment]
> It's incompatible with Windows XP Server 2003/“R2,” Vista, Server 2008/R2 7 (right now). Use Windows 8, Server 2012/R2, 8.1, 10, Server 2016, Server 2019, 11, Server 2022 or Server 2025.

everything worked fine the last time i used it on windows 7 (literally the day before i made this issue)
and i'm using the same version as i did for that time

**Comment by ftde0** [comment]
try running yt2009setup from the directory (B:\oldyt) directly. if not work, run `npm install` and try again. if still no worky, sometimes npm junks itself so you may need to put all dependencies into the command, so `npm install express google-protobuf maxmind-db-reader node-fetch@2.6.7 node-html-parser@5.3.3 readline-sync ytdl-core ws`.

**Comment by Pwnz0rserver2009** [comment]
> try running yt2009setup from “the” directory (B:\oldyt) directly. if not work, run `npm install` and try again. if still no worky, sometimes npm junks itself so you may need to put all dependencies into the command, so `npm install express google-protobuf maxmind-db-reader node-fetch@2.6.7 node-html-parser@5.3.3 readline-sync ytdl-core ws`.

as for the first suggestion, that's what i always do to run yt2009 ._.
for the second, yay it fixed it :3 somehow yt2009 broke all dependencies by simply running with a watch.html it didn't like

**Comment by mrkrabs206** [comment]
> try running yt2009setup from the directory (B:\oldyt) directly. if not work, run `npm install` and try again. if still no worky, sometimes npm junks itself so you may need to put all dependencies into the command, so `npm install express google-protobuf maxmind-db-reader node-fetch@2.6.7 node-html-parser@5.3.3 readline-sync ytdl-core ws`.

Read this: https://github.com/ftde0/yt2009/issues/131 (don't worry no spam)
