### ISSUE TITLE
Video qualities, annotations, captions, endscreens/related videos, profile pictures, theater mode, sharing (and channel name and view counter on 2014) do not show/work on mid 2013-mid 2015 players.

### ISSUE THREAD

**Issue by gigigigi53** [ftde0/yt2009#142]
Don't worry, the AS3 modules incident will be fixed, but now let's talk about this one now.

So, on the mid 2013-mid 2015 players, a lot of features are missing or broken.
On this list is the features that do not show or work at the moment on these AS3 players:
1. Video qualities (all players)
2. Annotations (all players)
3. Captions (all players)
4. Endscreens/related videos (all players)
5. Profile pictures (mid 2013-late 2014)
6. Theater mode (all players)
7. Sharing (all players)
8. Channel name (2014 players)
9. View counters (2014 players)

I don't know why this happens for no/some reason. I tried the one from 2010 (subtitles3, iv3 and endscreen) and 2012 (the same, but with/without endscreen), but nothing seems to work. It's sort of like this:

![Screenshot 2024-09-27 203054](https://github.com/user-attachments/assets/a9361694-0d78-4017-a181-ce61828307cc)
(Video player)

![Screenshot 2024-09-27 203111](https://github.com/user-attachments/assets/80c4f5a1-30c8-43c4-8d22-c2a4dbe2c38f)
(Video information)

![Screenshot 2024-09-27 203208](https://github.com/user-attachments/assets/f80f5271-10e8-444a-9b1e-7b50fb2c7ce9)
(Endscreen)

And it doesn't look like a normal player, more of an embedded one to be honest.

BTW, these were tested on late 2013. So, this could be the same or different story as the 2005 players incident regarding fullscreen and scrubber. But this time, with the broken or unavailable features.

We would need to make a way to redirect these features to act as a normal player and not a cheap embedded one.
The modules will have diff. names like the 2009, 2010 and 2012 ones inside swf code in the watch page. Hopefully that stands out. Bye.

**Comment by ftde0** [comment]
exactly! you'll be the one to fix your god damn flash player SWFs because you can't set them up correctly and then COMPLAIN TO **ME** that they don't work as you'd want them to.

don't even try to make any new issue on as3 flash player.

**Comment by gigigigi53** [comment]
Oh, and how do I delete these?
