### ISSUE TITLE
Nextube interferance

### ISSUE THREAD

**Issue by Caveproject** [ftde0/yt2009#145]
Hi, Is there a possibility in the near future to add the latest Youtube interference implemented into Nextube Wii? It would have a more clean and vibrant look. It's ok whether some features may be overly optimized.

**Comment by ftde0** [comment]
nextube is its own thing, only based on yt2009. i don't maintain it. if you wanted the later youtube ui, you'd probably be left with heavily modifying the flash files, which is not something me (and most likely others behind a fork) will focus on.

**Comment by erievs** [comment]
Yeah, NexTube is not that same as YT2009, it is a fork of YT2009. They're some changes to the backend that has had to be made and such. You can use NexTube which I'll always try to keep up to date here, use stock Yt2009 and add the changes yourself to the backend.

**Comment by erievs** [comment]
The interface is a flash file called leanbacklite_wii.swf. And it requires videos in WebM for proper Wii playback, it is possible to run it with MP4s a bit easier, but you'd be stuck on a browser. That's why NexTube is a fork, since they're backend changes that are needed.
