### ISSUE TITLE
ftde0 give me a token for http://yt09.giabs.lt/auth.html 

### ISSUE THREAD

**Issue by hollyperley23** [ftde0/yt2009#149]
ftde0 please give me a token  for yt09.giabs.lt

**Comment by ftde0** [comment]
https://github.com/user-attachments/assets/edc1f3a8-8fb8-4d9c-b3f2-e26bbf71a0a3

**Comment by Ziulkarz** [comment]
oczywiście że ten konkretny odcinek jak ja dobrze cię znam

**Comment by 2ktan** [comment]
XDDDDDDDDDD

**Comment by gigigigi53** [comment]
wtf..
