### ISSUE TITLE
ftde0 actually give me a token for http://yt09.giabs.lt 

### ISSUE THREAD

**Issue by hollyperley23** [ftde0/yt2009#150]

**Comment by uraniumenjoyer** [comment]
bro stfu and stop spamming issues

**Comment by hollyperley23** [comment]
ftde0 what's your discord

**Comment by ftde0** [comment]
https://github.com/user-attachments/assets/90b31d18-1837-4d0d-944f-ee2501a0865a

**Comment by Szprinktrap** [comment]
> ftde0 what's your discord

bro do you really think he has keys to every single yt2009 instance

**Comment by Radiatorgaming420** [comment]
> VID_20241016_084930.mp4

why noone answer to an actual issue i made, but yall respond to some guy spamming issues for tokens cause hes too lazy to host his own
