### ISSUE TITLE
how do i shutdown this?

### ISSUE THREAD

**Issue by john123903** [ftde0/yt2009#151]
I was trying to stop it because i accidentally started it. there is no way of disabling it, so I decided to restart my computer. is there a way to stop this or not?

**Comment by Gladosator** [comment]
You mean like pressing control C? Cuz it’s just a command prompt program.. so it’s just like for all shell programs and commands, if you want something to stop running you press control C… or if you’re using docker then you list the running containers with ‘ docker ps ‘ and then use ‘docker stop [container id here] ‘ to stop the container.

**Comment by ftde0** [comment]
> You mean like pressing control C? Cuz it’s just a command prompt program.. so it’s just like for all shell programs and commands, if you want something to stop running you press control C… or if you’re using docker then you list the running containers with ‘ docker ps ‘ and then use ‘docker stop [container id here] ‘ to stop the container.

thanks for helping that guy out! closing as there doesn't seem to be anything else to do, feel free to reopen/make a new issue if further help is needed.
