### ISSUE TITLE
suggestion: documentation for creating a layout for yt2009?

### ISSUE THREAD

**Issue by Pwnz0rserver2009** [ftde0/yt2009#152]
i was trying to port a different youtube layout to yt2009, but it keeps crashing and i have no idea why
...documentation please?

**Comment by ftde0** [comment]
most HTML files to be edited are in the root directory (watch.html, channelpage.htm etc), with some in root/static_pages. most "fillable" parts of websites (such as related videos for watchpages) are in `back/yt2009templates.js`. custom layouts are not within the scope of yt2009.

close if no further questions.

**Comment by Pwnz0rserver2009** [comment]
> close if no further questions.

unrelated to layouts but what's the purpose of tokens and why does yt2009 complain if you leave a comment despite yt2009 obviously not being able to interact with the youtube account api (unless it does O_o)

**Comment by Pwnz0rserver2009** [comment]
is there any way to help debug layout bugs i end up creating or do i just have to deal with it

**Comment by Pwnz0rserver2009** [comment]
> is there any way to help debug layout bugs i end up creating or do i just have to deal with it

welp i guess no help
