### ISSUE TITLE
Timed out when downloading favicon.ico

### ISSUE THREAD

**Issue by idon69** [ftde0/yt2009#153]
as the title said

C:\Users\Administrator\Desktop\yt2009-main>node post_config_setup.js
== checking external tool: ffmpeg
== checking external tool: magick
== checking external tool: convert
creating cache files
== generating innertube data
useragent not found in config, using "Mozilla/5.0 (Windows NT 10.0; Win64; x64;
rv:102.0) Gecko/20100101 Firefox/102.0"
if you wish to use your own user agent,add a userAgent entry to config.json.
writing to constants
=== !!! ===
/back/yt2009constants.json was modified to include unique data.
this data may include the used useragent, your ip and others.
make sure to remove such data if you intend on sharing your copy.
=== downloading assets ===

skipping master-vfl121679.png, file exists

skipping video_bar_arrows-vfl84478.png, file exists

downloading favicon.ico (3/59)

C:\Users\Administrator\Desktop\yt2009-main\node_modules\node-fetch\lib\index.js:
1501
                        reject(new FetchError(`request to ${request.url} failed,
 reason: ${err.message}`, 'system', err));
                               ^
FetchError: request to http://web.archive.org/web/20091121010820if_/http://www.y
outube.com/favicon.ico failed, reason: connect ETIMEDOUT 207.241.237.3:80
    at ClientRequest.<anonymous> (C:\Users\Administrator\Desktop\yt2009-main\nod
e_modules\node-fetch\lib\index.js:1501:11)
    at ClientRequest.emit (node:events:519:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:2
1) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}

Node.js v20.18.0

C:\Users\Administrator\Desktop\yt2009-main>

**Comment by ftde0** [comment]
happened because the wayback machine (source for a few resources) was down. should be good now that its back. reopen if the issue keeps happening/any further questions.
