### ISSUE TITLE
Suggestion: Change the favicon to use the 2005-2010 not the 2010-2011 one

### ISSUE THREAD

**Issue by gigigigi53** [ftde0/yt2009#155]
This https://s.ytimg.com/yt/favicon-vfl1123.ico
aka ![favicon-vfl1123](https://github.com/user-attachments/assets/f7eeed19-d9bf-4a03-9bec-bb73337c224d)

**Comment by gigigigi53** [comment]
This makes it more accurate!

**Comment by ftde0** [comment]
the same archive used as a base for yt2009's watch has the one currently in the code.
http://web.archive.org/web/20090927150841/http://www.youtube.com/watch?v=jNQXAC9IVRw

**Comment by gigigigi53** [comment]
> the same archive used as a base for yt2009's watch has the one currently in the code. http://web.archive.org/web/20090927150841/http://www.youtube.com/watch?v=jNQXAC9IVRw

ugh sorry, but thanks...
