### ISSUE TITLE
APK crashes on startup

### ISSUE THREAD

**Issue by CubeFun** [ftde0/yt2009#16]
Hello, i have been trying to make the app work but it always crashes. I tried this on youtube 2.1.6 
I changed the padding and the api like this:
 const-string v0, "AES/ECB/ZeroBytePadding"
    const-string v0, "http://192.168.240.45/youtube/accounts/registerDevice?developer=%s&serialNumber=%s"
    const-string v1, "http://192.168.240.45/"
    const-string v1, "http://192.168.240.45"
The port my yt2009 is on is 80 so i dont know what i did wrong

**Comment by ftde0** [comment]
don't put http/full path where "gdata.youtube.com" was. just the ip/domain. in your case
```
const string v1, "192.168.240.45"
```

**Comment by CubeFun** [comment]
> don't put http/full path where "gdata.youtube.com" was. just the ip/domain. in your case
> 
> ```
> const string v1, "192.168.240.45"
> ```

Ok i did this. The app doesnt crash anymore but many things dont work like
-things that work
-searching
-visiting channels 

-things that dont work
-videos
-homepage
-comments

In cmd when i the homepage tries to load it throws an error but when i try playing a videi it just keeps loading and no error message appears

**Comment by ftde0** [comment]
make sure you've entered your ip in config.json right. the app depends on it to get things like video comments and video playback itself.

it NEEDS to be an ip your device can reach. try experimenting with your local ip/external if public instance.

you can modify the config.json and restart yt2009 to do that. no need to redo yt2009setup.

**Comment by ftde0** [comment]
by the lack of response i'm assuming this isn't a problem anymore. closing. feel free to reply/create a new issue if needed.
