### ISSUE TITLE
Android homepage doesnt work

### ISSUE THREAD

**Issue by CubeFun** [ftde0/yt2009#163]
Hi, not sure if this is my problem but on YouTube version 3.5.5 the homepage doesnt work, but searching for videos work, and playback.

Things i tried - Made a fresh new install of yt2009, tried the app on my phone and on another device, patched another app with https://yt2009.aesthetiful.com/ and tried that and the same result.
Also i downloaded the latest version of yt2009, in my case yt2009-wii and i logged into my account succesfully.

Not sure if this helps but these are the devices that i tried the app on - Xiaomi Redmi Note 11 Pro 5G Android 13, Nexus 7 (2013) Android 4.4.2.

**Comment by ftde0** [comment]
sounds like it's not a problem on your end, will be fixed. thanks for the reportt!

**Comment by ftde0** [comment]
should be good now. can you update your yt2009 and check? feel free to close if all working.

**Comment by CubeFun** [comment]
![Screenshot_2024-12-01-15-56-45-441_com sliplane5 android youtube](https://github.com/user-attachments/assets/b0cbf46a-0d8b-412f-aeb8-8986644c8150)
It still doesnt seem to work :( Before when i hit "try again" a loading wheel appeared for 2 seconds, but now when i click try again nothing happens, not sure why :(((

**Comment by ftde0** [comment]
..huh.
can you open this url: `view-source:http://<your_instance_url>/feeds/api/standardfeeds/recently_featured` and send the response here?

**Comment by ftde0** [comment]
ah, great!
> Is there a way to make more videos appear on the homepage?

iirc there is room for around 25 vids on the homepage, watch some old videos on web yt2009 with the `homepage_contribute` flag or wait for more vids to come through the now-fixed sync.

> Will there ever be added caption support for android?

captions support was discussed multiple times before. they would need full video data to be available instantly, which with 20-25 videos per feed is simply not fast or viable, and would likely result in requests getting timed out all the time.

captions are not happening in mobile.

**Comment by CubeFun** [comment]
Okay, thanks for the reply!
