### ISSUE TITLE
Video loading error on android 2.3

### ISSUE THREAD

**Issue by hikeri** [ftde0/yt2009#164]
When trying to watch any video using android 2.3 (YouTube ver 2.1.6), an error occurs during playback. Although on the modern Android version everything works. Traffic scanning doesn't show anything, but I'll attach it instead. Traffic scan:

The Phone sent:
```
GET /channel_fh264_getvideo?v=CtwJvgPJ9xw HTTP/1.1
Host: my.url.com
Bandwidth: 11000000
User-Agent: HTC Streaming Player htc_nld / 1.0 / htc_pico / 2.3.5
x-network-type: WIFI
x-wap-profile: http://www.htcmms.com.tw/Android/Common/PJ03/ua-profile.xml
```

The Server sent:
```
HTTP/1.1 302 Found
Server: nginx
Date: Sun, 01 Dec 2024 19:18:09 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 45
Connection: keep-alive
X-Powered-By: Express
Location: /assets/CtwJvgPJ9xw.mp4
Vary: Accept

Found. Redirecting to /assets/CtwJvgPJ9xw.mp4
```

**Comment by ftde0** [comment]
thanks for attaching the traffic!

android versions below 4.2 need videos to be reencoded to play.
a check for old android versions is performed, but with custom user agents (like the one sent by your device) such check can't always be reliable.

i'll try to address this with some kind of a list of those non-standard user-agents in a future version.

**Comment by ftde0** [comment]
@hikeri not sure if it let you know, should be good now, please test and close if all good
