### ISSUE TITLE
Having trouble setting up the second step of setting up a yt2009 apk (changing the strings issue) yt2009 apk

### ISSUE THREAD

**Issue by Techfromthepast123** [ftde0/yt2009#19]
So for the changing strings part,from the directory where the decompiled youtube apk and apktool.bat and apktool.jar. Whenever I try to run the command "grep -r -i "registerDevice" it does nothing and no there are no error screens or something like that in the cmd when I press enter it's just blank nothing pops up.

**Comment by jackhacksren** [comment]
https://sourceforge.net/projects/grep-for-windows/files/

this is the part where the creator used the grep to make that guide

also add it to ur PATH found in enviroment variibles

**Comment by Techfromthepast123** [comment]
Thank you !
