### ISSUE TITLE
Issues with opening channels

### ISSUE THREAD

**Issue by TheOnlyOne12315** [ftde0/yt2009#21]
I was using yt2009 and I tried to go to a channel (idurl/user/Shedletsky) it completely broke yt2009 and node.js and the only way to fix it was by repairing node.js through the installer. I'm not having problems with this but I want to report it. Also, it only has happened with John Shedletsky's channel
Logs:
   ==========

    yt2009 - dev

    ==========
    launch time: 23:30

() mainpage 1701577811864
() Rxxf71qCkB4 clean fetch 1701577812124
() 6BA3vZR4ibY clean fetch 1701577812231
() Td8-oj-DgeM z cache (1701577812234)
(exp_related) clubpenguin  before:2010-04-01 from cache 1701577813395
(exp_related) roblox rube  before:2010-04-01 clean fetch 1701577813407
(exp_related) scatman's  before:2010-04-01 clean fetch 1701577814081
() mainpage 1701577849160
() Rxxf71qCkB4 z cache (1701577849303)
() 6BA3vZR4ibY z cache (1701577849304)
() Td8-oj-DgeM z cache (1701577849305)
(exp_related) scatman's  before:2010-04-01 from cache 1701577849849
(exp_related) roblox rube  before:2010-04-01 from cache 1701577849928
(exp_related) clubpenguin  before:2010-04-01 from cache 1701577850122
() Roblox before:2008-12-03 clean fetch 1701577852221
() Roblox trailer before:2008-12-03 clean fetch 1701577861938
() channel channel/UC4dOFHrcqbhrf9yrNUN13cw
() "John Shedletsky" before:2008-12-03 before:2008-12-03 clean fetch 1701577865423
C:\Users\Danie\Downloads\yt2009-main\yt2009-main\back\dominant_color.js:30
        output = output.split("(")[1].split(")")[0].split(",")
                                     ^

TypeError: Cannot read properties of undefined (reading 'split')
    at C:\Users\Danie\Downloads\yt2009-main\yt2009-main\back\dominant_color.js:30:38
    at ChildProcess.exithandler (node:child_process:414:7)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:514:28)
    at Pipe.<anonymous> (node:net:337:12)

Node.js v20.10.0

**Comment by ftde0** [comment]
make sure you've installed convert correctly and didn't just bypass its requirement.

**Comment by TheOnlyOne12315** [comment]
Thank you every much :)

**Comment by TheOnlyOne12315** [comment]
It's fixed now but Shedletsky's channel still breaks yt2009.
