### ISSUE TITLE
Problems with the flash players

### ISSUE THREAD

**Issue by TheOnlyOne12315** [ftde0/yt2009#23]
I am having problems with the Flash players. I patched the Flash player (2006 - 2008 is the one I want to use) and it just says Loading... forever and doesn't load the video. Side note this is not due to flash emulators not working as I'm using pale moon.

**Comment by TheOnlyOne12315** [comment]
Sometimes it also shows the classic loading circle

**Comment by TheOnlyOne12315** [comment]
How do I get to the network tab? (On pale moon)

**Comment by TheOnlyOne12315** [comment]
I also enabled h264 (Don't know if it will help) and it didn't help

**Comment by TheOnlyOne12315** [comment]
It's showing stuff but none of the ones you listed

**Comment by ftde0** [comment]
you could try setting up a crossdomain.xml. there is an older /crossdomain.xml in the repo used in early development, feel free to mess around.
[https://www.adobe.com/devnet-docs/acrobatetk/tools/AppSec/xdomain.html#typical-policy](https://www.adobe.com/devnet-docs/acrobatetk/tools/AppSec/xdomain.html#typical-policy)

if that fails, most likely a bad patch.

**Comment by TheOnlyOne12315** [comment]
Can you leave a download link for cross-domain Idk how to make XML files properly

**Comment by TheOnlyOne12315** [comment]
The SWF file is sending messages to vidlii

**Comment by ftde0** [comment]
crossdomain allowing everything for troubleshooting:
```
<cross-domain-policy>
    <allow-access-from domain="*" secure="false"/>
</cross-domain-policy>
```
save to your crossdomain.xml. if that works make a proper crossdomain if you're hosting a public instance.

if still fails, bad patch. read the flash player doc CAREFULLY. don't patch it to vidlii!!! you want to patch it to your yt2009 instance.

**Comment by TheOnlyOne12315** [comment]
Thanks for the code, what I mean by "The SWF file is sending messages to vidlii" is that when I was patching the SWF file it had the links set to vidlii and not youtube "Yes I did change the links to the localhost IP"

**Comment by TheOnlyOne12315** [comment]
Where should I put the crossdomain

**Comment by TheOnlyOne12315** [comment]
I just figured the file I used was the vidlii player from when they used Flash. I need to find the original player and see where the problem goes. Do you know where I can find it?

**Comment by ftde0** [comment]
i'm lost, the original 2006 swf (with a different url at most) and the instructions to patch it are in the repo ([alt-swf](https://github.com/ftde0/yt2009/tree/main/alt-swf)). the instructions are at [flash_player_patch.md](https://github.com/ftde0/yt2009/blob/main/flash_player_patch.md). how you're messing around with vidlii? what does vidlii have to do with all of this?

read the flash player patch CAREFULLY and THOROUGHLY.

**Comment by TheOnlyOne12315** [comment]
The 2006 swf file I was using was the vidlii player not the original. And yes I read the instructions

**Comment by TheOnlyOne12315** [comment]
crossdomain crashed node.js what happened?

**Comment by ftde0** [comment]
i'm concerned you're doing something wrong.

crossdomain.xml won't crash the whole frontend.

did you follow the instructions i gave you previously? i mentioned looking through the network tab to pinpoint what's going wrong and you didn't seem to use the info from that.

please repatch the player. if a crash keeps happening send the full log so i can get an idea of what's happening.

**Comment by TheOnlyOne12315** [comment]
Fixed it player's working now :D

**Comment by TheOnlyOne12315** [comment]
Bruh patched it right now
