### ISSUE TITLE
Flash player not working

### ISSUE THREAD

**Issue by MattRTGB** [ftde0/yt2009#26]
When I use html player it works just fine

But when I use Flash, I get this

![image](https://github.com/ftde0/yt2009/assets/84507847/4c287b88-2a84-420b-8af5-a8b286de40d2)

It's the same for every video.
I'd love some help, thanks!

**Comment by ftde0** [comment]
sounds like you didn't patch the flash player. for base functionality patch the /watch.swf player by following [this guide](https://github.com/ftde0/yt2009/blob/main/flash_player_patch.md).

**Comment by MattRTGB** [comment]
> sounds like you didn't patch the flash player. for base functionality patch the /watch.swf player by following [this guide](https://github.com/ftde0/yt2009/blob/main/flash_player_patch.md).

Hey, thanks for replying!
I thought about that too but I also thought that it was already pre-patched. I will try tomorrow, thanks again!

**Comment by MattRTGB** [comment]
> sounds like you didn't patch the flash player. for base functionality patch the /watch.swf player by following [this guide](https://github.com/ftde0/yt2009/blob/main/flash_player_patch.md).

Hey, I patched it and it works fine on the site but if I open the swf by itself (e.g. http://[ip]/watch.swf?video_id=i8dh9gDzmz8&) it says the same thing.

**Comment by ftde0** [comment]
when opening the swf by itself, are you requesting it at the same ip you're using the site on?

for example, let's say this is your watchpage link:
```
http://127.0.0.1/watch?v=KwSsEdbP8uQ
```
and that works with flash, when trying the swf by itself, it should also be at 127.0.0.1:
```
http://127.0.0.1/watch.swf?video_id=KwSsEdbP8uQ
```
otherwise the flash player will see it as a different site (even if it's a http/https difference) and would need proper crossdomain.xml (and possibly some mentions of the new site in the swf itself) to be set to function.

**Comment by MattRTGB** [comment]
Yes
![image](https://github.com/ftde0/yt2009/assets/84507847/ed6446c4-f5e2-4b90-9c82-0b93bcecbbc9)

![image](https://github.com/ftde0/yt2009/assets/84507847/9af1dfeb-8867-4037-8e65-eb8229e9de5b)

**Comment by ftde0** [comment]
what if you add `/mp4` to the end of the video id? that sends a h264 mp4.

also try checking the console window, maybe you have an error showing up when you try to load the video. if so, send it here so i can have a closer look on what's going on.

**Comment by MattRTGB** [comment]
> what if you add `/mp4` to the end of the video id? that sends a h264 mp4.
> 
> also try checking the console window, maybe you have an error showing up when you try to load the video. if so, send it here so i can have a closer look on what's going on.

![image](https://github.com/ftde0/yt2009/assets/84507847/4e38b917-bd36-4339-989f-3b8861edfe74)

this is when using normal link (I don't know why it doesn't download the flv file)

![image](https://github.com/ftde0/yt2009/assets/84507847/74d435a2-1b89-49a5-94a8-99faa98ff5f9)

and this is when using /mp4 (it gets the video file but there's still this error with "player 204"

**Comment by ftde0** [comment]
so the video does play with `/mp4`?

do you have any errors in the command prompt/terminal running yt2009 when trying to download .flv? (send the screenshot of it if so) assuming you're playing the same video with `/mp4` and it works and it just doesn't with flv, i'd check if ffmpeg is there and you didn't bypass the requirement.

there used to be a bug where on the post_config_setup phase tools weren't detected correctly, would throw false errors about tools not being there and one way was to bypass the detection. it's been fixed since then though.

/player_204 is not something that was necessary for videos to play so it wasn't implemented.

**Comment by MattRTGB** [comment]
> so the video does play with `/mp4`?
> 
> do you have any errors in the command prompt/terminal running yt2009 when trying to download .flv? (send the screenshot of it if so) assuming you're playing the same video with `/mp4` and it works and it just doesn't with flv, i'd check if ffmpeg is there and you didn't bypass the requirement.
> 
> there used to be a bug where on the post_config_setup phase tools weren't detected correctly, would throw false errors about tools not being there and one way was to bypass the detection. it's been fixed since then though.
> 
> /player_204 is not something that was necessary for videos to play so it wasn't implemented.

No, it doesn't play with "/mp4" and in the terminal there isn't any error or line showing up

**Comment by TheOnlyOne12315** [comment]
What client are you trying to patch?

**Comment by MattRTGB** [comment]
> What player are you trying to patch?

I started with the default one (should be 2009)

**Comment by TheOnlyOne12315** [comment]
So you're trying to patch the 2008 player? (2008 player was used from 2008 - 2010)

**Comment by TheOnlyOne12315** [comment]
> > So you're trying to patch the 2008 player? (2008 player was used from 2008 - 2010)
> 
> I guess so

Please let me know why you're trying to patch the 2008 player. we have the HTML player

**Comment by MattRTGB** [comment]
> > > So you're trying to patch the 2008 player? (2008 player was used from 2008 - 2010)
> > 
> > 
> > I guess so
> 
> Please let me know why you're trying to patch the 2008 player. we have the HTML player

I wanted to patch the flash player because I wanted to test the frontend on windows xp

**Comment by TheOnlyOne12315** [comment]
> I wanted to test the frontend on windows xp

I've just got the 2008 player working. If you want download I can leave one

**Comment by MattRTGB** [comment]
> > I wanted to test the frontend on windows xp
> 
> I've just got the 2008 player working. If you want download I can leave one

I'd like to try, thanks.

**Comment by TheOnlyOne12315** [comment]
https://www.mediafire.com/file/w1o51uyo0uie8yy/2008.swf/file

**Comment by MattRTGB** [comment]
> https://www.mediafire.com/file/w1o51uyo0uie8yy/2008.swf/file

same thing, nada.

**Comment by TheOnlyOne12315** [comment]
Que raro, For me it works. One thing is that flash emulators don't work (eg. ruffle)

**Comment by MattRTGB** [comment]
> Que raro, For me it works. One thing is that flash emulators don't work (eg. ruffle)

Yeah I know, I'm using Adobe Flash Player 32 on PaleMoon

**Comment by TheOnlyOne12315** [comment]
This may have to do with the flash player being too new, I'm using flash 17

**Comment by MattRTGB** [comment]
> This may have to do with the flash player being too new, I'm using flash 17

I'll try right away

**Comment by TheOnlyOne12315** [comment]
Flash 17.0.0.134

**Comment by TheOnlyOne12315** [comment]
No, But download Pale Moon 32.5.1 which is the version I'm using with Flash 17.0.0.134

**Comment by MattRTGB** [comment]
> No, But download Pale Moon 32.5.1 which is the version I'm using with Flash 17.0.0.134

it doesn't work ):

**Comment by TheOnlyOne12315** [comment]
> > No, But download Pale Moon 32.5.1 which is the version I'm using with Flash 17.0.0.134
> 
> it doesn't work ):

Welp sorry, I can't give you further help then. Holp you patch it!

**Comment by ftde0** [comment]
for the record, the player still works on the watch page, right?
network tab in devtools? open it **before** loading the player's swf. feel free to screenshot the full log. if sending a screenshot don't miss any entries.

**Comment by MattRTGB** [comment]
> > > No, But download Pale Moon 32.5.1 which is the version I'm using with Flash 17.0.0.134
> > 
> > 
> > it doesn't work ):
> 
> Welp sorry, I can't give you further help then. Holp you patch it!

Hey, I tried doing the "/mp4" now and it worked, thanks man!
Also does the /mp4 thing work with every client? And could that be used aside from the frontend?

**Comment by ftde0** [comment]
i've tested `/mp4` as far back as the 2006 player and it works there. it may work on earlier ones but not tested.

it's a feature of the frontend itself so it will work if you patch the player to a different instance of yt2009, but if someone else implements their own way of getting those players working (outside of yt2009) it won't work unless they specifically add `/mp4` support to their server.

`/mp4` will also be used when enabling h264 on /toggle_f. will make your videos load faster as it doesn't have to reencode videos to .flv.

**Comment by TheOnlyOne12315** [comment]
> i've tested `/mp4` as far back as the 2006 player and it works there. it may work on earlier ones but not tested.
> 
> it's a feature of the frontend itself so it will work if you patch the player to a different instance of yt2009, but if someone else implements their own way of getting those players working (outside of yt2009) it won't work unless they specifically add `/mp4` support to their server.
> 
> `/mp4` will also be used when enabling h264 on /toggle_f. will make your videos load faster as it doesn't have to reencode videos to .flv.

For what I've used my players only work in h264 mode, It doesn't matter. And I've got e2006 to work with /mp4

**Comment by MattRTGB** [comment]
Oh alright, thanks again!
