### ISSUE TITLE
yt2009 page on youtube.com looking broken

### ISSUE THREAD

**Issue by nope312** [ftde0/yt2009#3]
![2023_11_16_0zl_Kleki](https://github.com/ftde0/yt2009/assets/65314830/6793187d-e439-472f-b810-ccac49824df7)
i used fiddler to make it go onto youtube.com, on the localhost it looks fine but on youtube it looks broken. I reinstalled it, but the same result.

**Comment by ftde0** [comment]
yt2009 isn't designed to be put over youtube.com as of yet. for the time being you can host yt2009 from another pc and set up your main pc to proxy youtube.com to the address of the pc the frontend is hosted on.
