### ISSUE TITLE
How to patch Fullscreen for 2006 player

### ISSUE THREAD

**Issue by TheOnlyOne12315** [ftde0/yt2009#33]
Kinda useless issue but it doesn't work and the 2006 player is way too small for my liking

**Comment by ftde0** [comment]
[2006 - Copy.zip](https://github.com/ftde0/yt2009/files/13779557/2006.-.Copy.zip)
try this one. it's a later version of the player that should work with fullscreen.
it's set to 192.168.1.7 so keep that in mind when setting it up for your instance.

if this ends up working, let me know and feel free to close the issue so i can merge this in.

**Comment by TheOnlyOne12315** [comment]
I use 127.0.0.1 with port 80. Can you repatch it for that IP :3

**Comment by TheOnlyOne12315** [comment]
I repatched for the IP I'm using and Fullscreen still doesn't work

**Comment by TheOnlyOne12315** [comment]
The player doesn't even load

**Comment by ftde0** [comment]
i repatched the player for 192.168.1.7 and tested it right before i sent the previous message and it works nicely for me, including fullscreen. are you sure you aren't messing anything else up?

to reiterate
- do a text search for `192.168.1.7`, replace ALL occurences with your ip
- save. you can replace `/alt-swf/2006.swf` with your new swf
- if saved as `/alt-swf/2006.swf`, load the `standard 2006 player` prefix from /toggle_f. save your preference.
- load a video and watch.

if still not working, send me a screenshot of the watchpage including the network tab (devtools -> `Network` tab at top) so i can have a look.

**Comment by ftde0** [comment]
there is a whole lot more in the network tab, the top stuff doesn't say much. in the meanwhile however, does the video player open when going to:
ip:port/alt-swf/2006.swf?video_id=id/mp4
? prefilled for 127.0.0.1 and an example video:
http://127.0.0.1/alt-swf/video_id=XPoiPZYbtnA/mp4

**Comment by TheOnlyOne12315** [comment]
This is what happens when I go to http://127.0.0.1/alt-swf/video_id=XPoiPZYbtnA/mp4
![Uploading Screenshot 2023-12-29 140538.png…]()

**Comment by TheOnlyOne12315** [comment]
![Screenshot 2023-12-29 140538](https://github.com/ftde0/yt2009/assets/152047025/791d2f87-4b15-4f39-a8f8-114e02d67449)

**Comment by ftde0** [comment]
sorry i messed up the link
http://127.0.0.1/alt-swf/2006.swf?video_id=XPoiPZYbtnA/mp4

**Comment by TheOnlyOne12315** [comment]
Loads but no fullscreen

**Comment by TheOnlyOne12315** [comment]
![Screenshot 2023-12-29 141554](https://github.com/ftde0/yt2009/assets/152047025/e0eba5e8-a91c-40e7-a725-c18dcf67a935)
Repatched the player and it works now! thanks
*I'm not closing the issue until a respond so you can know :)*
