### ISSUE TITLE
downloads for the stuff required for the apk

### ISSUE THREAD

**Issue by cookies5219** [ftde0/yt2009#34]
like the title says i want like links to the sites

**Comment by cookies5219** [comment]
also does 2.4.4 work for it

**Comment by ftde0** [comment]
if using windows: https://sourceforge.net/projects/grep-for-windows/files/
https://apktool.org/
https://www.apkmirror.com/uploads/page/38/?appcategory=youtube
(if visiting from the future, click the Last page to find old APKs)

2.4.4 should work.
