### ISSUE TITLE
Channels Issue

### ISSUE THREAD

**Issue by thecinnsystem** [ftde0/yt2009#37]
Whenever I try and open a channels page, 9/10 times it will crash saying (using tomska as an example)

() channel user/tomska
convert: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/746.
convert: no images defined `histogram:info:' @ error/convert.c/ConvertImageCommand/3362.
() "TomSka" before:2008-12-22 before:2008-12-22 clean fetch 1703981800234
clean
/home/server/yt2009/back/dominant_color.js:30
        output = output.split("(")[1].split(")")[0].split(",")
                                     ^

TypeError: Cannot read property 'split' of undefined
    at /home/server/yt2009/back/dominant_color.js:30:38
    at ChildProcess.exithandler (child_process.js:299:7)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Socket.<anonymous> (internal/child_process.js:444:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:676:12)

**Comment by TheOnlyOne12315** [comment]
Did you download convert when setting up yt2009?

**Comment by thecinnsystem** [comment]
> Did you download convert when setting up yt2009?

Yep.

**Comment by TheOnlyOne12315** [comment]
> > Did you download convert when setting up yt2009?
> 
> Nope.
Which convert did you download?

**Comment by thecinnsystem** [comment]
I used the one built from the github repo for ImageMagick

**Comment by TheOnlyOne12315** [comment]
> I used the one built from the github repo for ImageMagick

Hmm try the one in the website

**Comment by thecinnsystem** [comment]
> > I used the one built from the github repo for ImageMagick
> 
> Hmm try the one in the website

I can’t find like an actual installable version for Debian based OSes on there, I’ll look again in a bit.

**Comment by ftde0** [comment]
> > > I used the one built from the github repo for ImageMagick
> > 
> > 
> > Hmm try the one in the website
> 
> I can’t find like an actual installable version for Debian based OSes on there, I’ll look again in a bit.

`apt install imagemagick`

**Comment by ftde0** [comment]
the issue will no longer crash the whole frontend as of https://github.com/ftde0/yt2009/commit/84db2c38770edccc1c969cd222f1afba42f093fb. installing convert correctly is still required to fully solve the problem.
