### ISSUE TITLE
Yt2009 tablet issue

### ISSUE THREAD

**Issue by CubeFun** [ftde0/yt2009#39]
Hello! I recently and succesfully patched the youtube apps to work with my server. The apps did work on mobile but on my old android tablet with android 4.2.2 didnt. Versions 2.1.6, 2.3.4, 2.4.4 did work on the tablet because they were displaying the mobile interface. But when i tried versions 3.3.3 and 3.5.5 they displayed a special interface for the tablet and the app didnt work. Any solutions?
![IMG_20240106_115451](https://github.com/ftde0/yt2009/assets/109980144/90e50d87-5789-4292-a9dd-f684a4ab21e5)

**Comment by ftde0** [comment]
i've seen the tablet ui work for people when i patched the apk for the private host. are you sure nothing's up with your tablet/patch?
you can install 3.x apps on mobile and they will appear as reskinned 2.x apps - that way you can check if your patch is good.

4.1.x apks will also show the tablet ui so feel free to try that.

**Comment by CubeFun** [comment]
Hello. You can see in the photo this is how the 3.5.5 app looks on my phone. It works well. And i dont think anything is wrong with the tablet since the wifi is normal and everything works properly. I know about the 4.1x apps since the 4.1.17 youtube came preinstalled with the tablet but it didnt work too. I think i just dont know how to patch it properly :( 
![Screenshot_2024-01-06-14-58-33-549_com google sndroid youtube](https://github.com/ftde0/yt2009/assets/109980144/27cb9e5f-363a-4fc1-b964-7b3abd2f7603)

**Comment by ftde0** [comment]
are your patches using https or http? for compatibility go for http if you don't have it already.

an easier way of knowing what's going on with your tablet you could set up a proxy on your pc and connect the tablet to it so you have an idea of what's happening. quite a lot of trial and error on that method tho

**Comment by CubeFun** [comment]
Well. I use sometimes my own yt2009 frontend which consists of the ip adress no https or http. But i patched most of the youtube apps to work with the yt2009 frontend (yt2009.giabs.ovh) which uses https. If i changed the https to http in the app would it do something?

**Comment by ftde0** [comment]
if you've set the patched app to use https a change to http is always worth a try if there is something wrong as there is less to go wrong, especially dealing with an old device (root certs, system time, host certs, you name it).

yt2009.giabs.ovh does support http so shouldn't be much trouble other than changing up https to http where needed.

**Comment by ftde0** [comment]
no response, closing for now. reopen if still needed.
