### ISSUE TITLE
FetchError: request to *Link* failed, reason: read ECONNRESET

### ISSUE THREAD

**Issue by LITE228** [ftde0/yt2009#4]
This happens when I try to go to a video or search something
What do I do?
![Безымянный](https://github.com/ftde0/yt2009/assets/97251902/c514861d-8562-4272-8708-00ee22361bdc)

**Comment by ftde0** [comment]
try with any proxys or anything that could interfere with your internet disabled. also check that everything with your connection is alright

**Comment by LITE228** [comment]
I disabled all extensions using proxies, restarted yt2009 (closed cmd and started node yt2009setup.js and node backend.js again) but the result remains the same

**Comment by FurblandChannel** [comment]
It’s been a while, does the problem still occur on the latest version?

**Comment by FurblandChannel** [comment]
If all else fails see if anything odd is showing up in Wireshark.

**Comment by ftde0** [comment]
fixed with https://github.com/ftde0/yt2009/commit/49869cd1a11f581a8a6be358a15766d53805860a.
