### ISSUE TITLE
BLZR PWA not working

### ISSUE THREAD

**Issue by FurblandChannel** [ftde0/yt2009#42]
When attempting to add the BLZR UI as a PWA, the page is not given the proper PWA attribute. This results in the page being added to the iOS Home Screen as a bookmark, not a PWA as intended.

**Comment by FurblandChannel** [comment]
When attempting to add the BLZR UI as a PWA, the page is not given the proper PWA attribute. This results in the page being added to the iOS Home Screen as a bookmark, not a PWA as intended.

**Comment by ftde0** [comment]
the term PWA wasn't really a thing until 2015-2016, whereas the blazer UI was available originally throughout 2010-2011. the original blazer's code is used just with minor changes to work with yt2009, thus no PWA attributes are present.

on top of that, a web UI from 2010 doesn't meet the PWA requirements, such as being usable offline. as it is, it's compatible with target devices of the time, such as older iOS versions (like 6) or early Android devices.

close if no further questions.

**Comment by FurblandChannel** [comment]
Got it.
