### ISSUE TITLE
[JUST A SUGGESTION, NOT A BUG] 1080p?

### ISSUE THREAD

**Issue by NockTwelve** [ftde0/yt2009#43]
Hi, while I was patching the flash players, I noticed code in them for 1080p, specifically from 2012-13 players, however when using them with yt2009, they only go up to 720p. Does the owner plan to add 1080p 
support sometime in the future?

**Comment by ftde0** [comment]
keeping open as a reminder to consider.

**Comment by NockTwelve** [comment]
Also you can close issue #29 as I got all flash players fixed up (you can
leave it open for others if they are having that issue)

**Comment by jackhacksren** [comment]
> Hi, while I was patching the flash players, I noticed code in them for 1080p, specifically from 2012-13 players, however when using them with yt2009, they only go up to 720p. Does the owner plan to add 1080p support sometime in the future?

so where is the conclusion to the issue #29 the part where it cant go past 360p that im tired

**Comment by NockTwelve** [comment]
> > Hi, while I was patching the flash players, I noticed code in them for 1080p, specifically from 2012-13 players, however when using them with yt2009, they only go up to 720p. Does the owner plan to add 1080p support sometime in the future?
> 
> so where is the conclusion to the issue #29 the part where it cant go past 360p that im tired

the conclusion was that on Actionscript 3 players you have to patch P-Code instead of Actionscript as it will corrupt the get_video_info and prevent quality options from showing, im trying to reach out to yt2009.giabs.ovh to tell them to repatch the alt-swf players of 2010.swf and 2012.swf with p-code instead of actionscript.

**Comment by ftde0** [comment]
1080p support was added with https://github.com/ftde0/yt2009/commit/963282f6167c5ec788446115958adf2ecb115ac1.
