### ISSUE TITLE
YT2009 stops working everytime I try and click a searched-for video

### ISSUE THREAD

**Issue by CarterSterling** [ftde0/yt2009#44]
Hello! I'm having a bit of a strange problem where I'm able to get yt2009 to work on my end - but every searched-for video just isn't working anymore. Here's a [video](https://gemoo.com/tools/upload-video/share/607057345112596480?codeId=P50VLw518LYkN&card=607057342277246976), so that you can see what I mean. Any help at all would be appreciated. Thanks!

**Comment by ftde0** [comment]
please attach a screenshot of your terminal/cmd output when the error happens for me to look into what's happening.

**Comment by ftde0** [comment]
no response for over a week. i'm guessing misconfigured magick/convert/ffmpeg/stuff. reopen if issue still happens and you have terminal/cmd output ready to send.
