### ISSUE TITLE
i am once again asking for HELP!!!! /subtitles not working/ 

### ISSUE THREAD

**Issue by jackhacksren** [ftde0/yt2009#48]
this is the video i use to test captions https://www.youtube.com/watch?v=UaTLQMFMfAI

[MYSWFS.zip](https://github.com/ftde0/yt2009/files/14012961/MYSWFS.zip)

i did follow ur guide of patching the subtitle module ive read it completly

**Comment by ftde0** [comment]
looks like in watch.swf / SubtitleModuleDescriptor the file name itself has an underscore `_` instead of a `-`. try changing that to the appropriate file name. in your case - `subtitle-module.swf` instead of `subtitle_module.swf`.

**Comment by jackhacksren** [comment]
> looks like in watch.swf / SubtitleModuleDescriptor the file name itself has an underscore `_` instead of a `-`. try changing that to the appropriate file name. in your case - `subtitle-module.swf` instead of `subtitle_module.swf`.

i tried to do that and it still doesnt work i did it both ways changing my swf to - and _ and the watch swf to also - and _ and both dont work

**Comment by jackhacksren** [comment]
e

**Comment by Endephis** [comment]
f
