### ISSUE TITLE
Instrukcja niejasna

### ISSUE THREAD

**Issue by Endephis** [ftde0/yt2009#51]
![2110697l](https://github.com/ftde0/yt2009/assets/33977446/6192496c-9178-4f65-8674-e1e4606af969)

**Comment by ftde0** [comment]
czarna s slychac wrum pod twoim blokiem

**Comment by Endephis** [comment]
oranzada helena

**Comment by Endephis** [comment]
jestem jak krupier przetasuje ciebie wzrokiem

**Comment by ftde0** [comment]
krew na betonie wszyscy ludzie obojetni coo?

**Comment by Endephis** [comment]
napaść pobicie kosy pokruszone zęby

**Comment by ftde0** [comment]
zero zero drifting na ostrzu noza

**Comment by Endephis** [comment]
daj kurwie miodu dziś jest ???? pożar

**Comment by ftde0** [comment]
bialo niebiescy zawsze beda jebani

**Comment by Endephis** [comment]
???? i zawsze chucznie chodzą z bandanami

**Comment by ftde0** [comment]
kreci boczki wegle suka

**Comment by Endephis** [comment]
kręci bączki szybciej od sonica

**Comment by ftde0** [comment]
robie ruchy dzwon po feata

**Comment by Endephis** [comment]
robie rozpierdol jak ?????????????????

**Comment by ftde0** [comment]
300c robie co chce zamykam licznik w sekunde lub dwie

**Comment by Endephis** [comment]
jak robie co chce to robie to na maxa ??? zakręta i już nie mam prawka

**Comment by ftde0** [comment]
prawda ale chuj z tym ma kopnac jak prawe ???

**Comment by Endephis** [comment]
jak lece to powyżej stówki na paliwo nigdy żadnej ????

**Comment by ftde0** [comment]
dopada ciebie strach i nie wiesz co sie dzieje

**Comment by Endephis** [comment]
to wszystko jak krew w piach, prosto sie w oczy smieje

**Comment by ftde0** [comment]
20 cali w snach obudza decybele
