### ISSUE TITLE
Error after running it for a while on Docker. 

### ISSUE THREAD

**Issue by itsmetin** [ftde0/yt2009#56]
After running it for a few hours using docker I get this error:

`[dev] using comments_viewmodel_parser instead
/yt2009/back/yt2009channels.js:274
                let shelfTitle = s.shelfRenderer.title.runs[0].text
                                                           ^
TypeError: Cannot read properties of undefined (reading '0')
    at /yt2009/back/yt2009channels.js:274:60
    at Array.forEach (<anonymous>)
    at Object.parse_main_response (/yt2009/back/yt2009channels.js:248:50)
    at /yt2009/back/yt2009channels.js:83:26
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

And then the container stops.

**Comment by ftde0** [comment]
i should be able to fix that later today, in the meanwhile you can change up your Dockerfile from
```
CMD ["node", "backend.js"]
```
to
```
CMD ["node", "backend_wrap.js"]
```
to automatically bring yt2009 back after any errors.

**Comment by breakgimme** [comment]
or alternatively, if you don't want to recreate your image from scratch you can also just add `--restart always` when creating the container so that it will always restart after it stops
