### ISSUE TITLE
Unable to make request to get video/comments...

### ISSUE THREAD

**Issue by VictorFilimonov** [ftde0/yt2009#58]
Hello! I have changed in youtube 3.5.5 all gdata.google.com to yt2009.org, all it works behind video and comments. In logcat I have got this: `03-08 17:22:28.782 W/YouTube ( 6644): Error for request {uri='http://undefined:80/feeds/api/videos/xW9_GmHJrro/comments?start-index=1&max-results=15', userAuth='null', headers='{}', content='null'} : java.net.UnknownHostException: Unable to resolve host "undefined": No address associated with hostname`
In [this](http://yt2009.org/feeds/api/videos/xW9_GmHJrro) xml undefined:80 also present. What I need to change???

**Comment by breakgimme** [comment]
hello, it's not your fault, it's probably due to a mistake i made in ced7c5f that prevented YT2009_IP from being set
5afde15 should fix this issue and it should start working for you after the admin of yt2009.org updates, sorry

**Comment by VictorFilimonov** [comment]
@breakgimme thank you 😊

**Comment by VictorFilimonov** [comment]
http://127.0.0.1:80/feeds/api/videos/w2yv8aT0UFc
Now I have this

**Comment by ftde0** [comment]
did you set your YT2009_IP either in the env? it defaults to 127.0.0.1 but if you intend to use the yt2009 app you should set it to an IP your mobile device can access (so if just using within your home network you can get by with just using your local  192.168.x.x IP, if using outside you should set it to your public IP, or domain name if used).

**Comment by VictorFilimonov** [comment]
Okay. Seems that admins from old-youtube.com have crooked arms :D

**Comment by breakgimme** [comment]
wanted to close this issue when yt2009.org gets the fix but its been 3 weeks and the admin doesn't seem to care, so i'll close it now

**Comment by VictorFilimonov** [comment]
New Instance...
https://yt2009-kcn6.onrender.com
