### ISSUE TITLE
(suggestion, not bug) YT2009 app patcher?

### ISSUE THREAD

**Issue by mrkrabs206** [ftde0/yt2009#59]
I'm just curious because there isn't any YT2009 app patcher.
Like this:
![yt2009 app patcher concept](https://github.com/ftde0/yt2009/assets/110676833/fd3505a3-65bf-421a-b2e5-b6e7c6955d81)

**Comment by ftde0** [comment]
https://github.com/ftde0/yt2009/blob/main/autoapk.js

**Comment by VictorFilimonov** [comment]
> https://github.com/ftde0/yt2009/blob/main/autoapk.js

It seems, @mrkrabs206 need patcher with GUI...

**Comment by mrkrabs206** [comment]
> https://github.com/ftde0/yt2009/blob/main/autoapk.js

Thank you!

**Comment by mrkrabs206** [comment]
now how to run this app?
steps?
ik, java.
