### ISSUE TITLE
Cannot read properties of undefined (reading 'includes') yt2009utils.js:372

### ISSUE THREAD

**Issue by aldairbotherotaku** [ftde0/yt2009#63]
I mean the error says everything, it seems like result.videoCountText.simpleText returns undefined.
i will use "result.subscriberCountText.simpleText.includes("subscriber"))" insted of that thing for make my instance work again lol

() rongu clean fetch 1710996153669
/repos/yt2009/back/yt2009utils.js:372
                && result.videoCountText.simpleText.includes("subscriber")) {
                                                    ^

TypeError: Cannot read properties of undefined (reading 'includes')
    at /repos/yt2009/back/yt2009utils.js:372:53
    at Array.forEach (<anonymous>)
    at Object.search_parse (/repos/yt2009/back/yt2009utils.js:284:17)
    at /repos/yt2009/back/yt2009search.js:199:49
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by ftde0** [comment]
judging by the message i'm guessing it happens when trying to search for "rongu"?

can you send the full search URL along with `back/yt2009constants.json` (remove your IP beforehand) so i can try to replicate the issue?

**Comment by Aldair502** [comment]
> judging by the message i'm guessing it happens when trying to search for "rongu"?
> 
> can you send the full search URL along with `back/yt2009constants.json` (remove your IP beforehand) so i can try to replicate the issue?
[file.json](https://github.com/ftde0/yt2009/files/14705915/file.json)

nah isn't my ip. it's a 1dll vps. anyways so there is no problem.

**Comment by ftde0** [comment]
will add a workaround tomorrow. once that's done i'll ask you to retest there.

**Comment by ftde0** [comment]
please retest and close if the issue is no longer there.

**Comment by aldairbotherotaku** [comment]
fixed
