### ISSUE TITLE
Struggling to use findstr on "registerDevice", "pkcs5padding", "gdata.youtube.com".

### ISSUE THREAD

**Issue by mrkrabs206** [ftde0/yt2009#65]
I am a complete noob on this **findstr** thing and I want to try to find out.
![noob at this grep](https://github.com/ftde0/yt2009/assets/110676833/671b4cbe-216e-49be-b178-e5bbe811b69f)

**Comment by ftde0** [comment]
looks like you've missed this part of apk_setup:
> ***and add a `[space] *` to the end of each command.***
so your command should look like this:
```
findstr -s -i "registerDevice" *
```
notice the ` *` at the end.

**Comment by mrkrabs206** [comment]
> looks like you've missed this part of apk_setup:
> 
> > _**and add a `[space] *` to the end of each command.**_
> 
> so your command should look like this:
> 
> ```
> findstr -s -i "registerDevice" *
> ```
> 
> notice the ` *` at the end.

Oh, thanks! I forgot lol. Now, how do I edit the .smali files? Can't I just use notepad?
