### ISSUE TITLE
(suggestions) Live videos, HD support (on mobile) and signing in (on mobile)?

### ISSUE THREAD

**Issue by mrkrabs206** [ftde0/yt2009#68]
Are these possible? If yes, do them, if not, don't do them. Thank you.

**Comment by ftde0** [comment]
- live: that was not a feature in 2009 as it's known today, thus it would be hard to implement.
there WAS a concept of "streams", but it was more of a video queue with everyone watching the same video at the same time. as cool as it seems there are no archives of streams working so those can't be recreated sadly.
- hd support on mobile: will consider, however it could be pretty limited as the apps need to know about the qualities before you even click on a video (and getting all videos' qualities in advance would be a HUGE time/resource/network hog)
- signin on mobile: login_simulate on mobile is already a thing you can enable to do things like comment on videos the same way as you can on the website. to do so:
    - log in on mobile with any account
    - connect your app with a web flag ui by going to `/mobile/app_connect.htm` on your instance you're using the app with.
    - once you've added your device, set the `login_simulate` flag as described on the page. (open `EXPORT MENU` on /yt2009_flags.htm, click `export session` to get your session token you use on the website and paste it into mobile flags).

**Comment by mrkrabs206** [comment]
> * live: that was not a feature in 2009 as it's known today, thus it would be hard to implement.
>   there WAS a concept of "streams", but it was more of a video queue with everyone watching the same video at the same time. as cool as it seems there are no archives of streams working so those can't be recreated sadly.
> * hd support on mobile: will consider, however it could be pretty limited as the apps need to know about the qualities before you even click on a video (and getting all videos' qualities in advance would be a HUGE time/resource/network hog)
> * signin on mobile: login_simulate on mobile is already a thing you can enable to do things like comment on videos the same way as you can on the website. to do so:
>   
>   * log in on mobile with any account
>   * connect your app with a web flag ui by going to `/mobile/app_connect.htm` on your instance you're using the app with.
>   * once you've added your device, set the `login_simulate` flag as described on the page. (open `EXPORT MENU` on /yt2009_flags.htm, click `export session` to get your session token you use on the website and paste it into mobile flags).

Thanks
