### ISSUE TITLE
Tablet UI on Android 5.x and later on 3.x is not working.

### ISSUE THREAD

**Issue by mrkrabs206** [ftde0/yt2009#71]
No, this is not by YT2009, Its by the tablet's ui on Android.

So, when I install any 3.x version of YouTube on a tablet (original or modded), it installs succesfully, on Android 3.0-4.4.4, it launches nicely, but on 5.0 and later Android versions, it launches, but it only shows a background and the YouTube logo.

https://new.reddit.com/r/oldyoutubelayout/comments/1bsivsq/tablet_version_of_youtube_330355_does_not_work_on/

The reason: `maybe the tablet ui has some additional files or urls`

How to fix it, and to make it work on newer android (tablet edition)?
![Screenshot_2024 02 06_00 11 39 865](https://github.com/ftde0/yt2009/assets/110676833/c00491f4-f84f-47c9-ae53-3afe07744fa2)

**Comment by ftde0** [comment]
the tablet ui requires graphics acceleration. looks like you're running it in a vm which could explain lack of the acceleration.

you're probably gonna get farther with android virtual device if you want to mess with tablet ui.

**Comment by mrkrabs206** [comment]
> the tablet ui requires graphics acceleration. looks like you're running it in a vm which could explain lack of the acceleration.
> 
> you're probably gonna get farther with android virtual device if you want to mess with tablet ui.

thank you
