### ISSUE TITLE
YT2009 patched apps do not work on older android (5.x and earlier) for no apparent reason.

### ISSUE THREAD

**Issue by mrkrabs206** [ftde0/yt2009#73]
@ftde0 

These don't work on older android versions. NO REASON WHY.

https://www.reddit.com/r/oldyoutubelayout/comments/1boflcm/my_244_youtube_patch_doesnt_work_on_44_android/

Update it to support older android. No sites will be affected. Not even the apps.

**Comment by mrkrabs206** [comment]
> how are they supposed to work if the instance used doesn't work in the first place? ![recentlyfeatured](https://private-user-images.githubusercontent.com/76792259/320229308-5a85431a-1424-4edd-88db-d337f3c4e4c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MzkwMDAsIm5iZiI6MTcxMjQzODcwMCwicGF0aCI6Ii83Njc5MjI1OS8zMjAyMjkzMDgtNWE4NTQzMWEtMTQyNC00ZWRkLTg4ZGItZDMzN2YzYzRlNGM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDIxMjUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwNGFjNzY4YmRiYmUzOTZhMGI0NmM2MjM3NTA0MzgwMGJiOWM0MWYxY2QxODYwYTdhNTcxY2JmZjkwMzE0NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EBibdN9jE6oEncg_k7ygYLx1dWQBPWlJWzHTvdXa_GU)

oops, wrong instance. What I meant is that it didn't work because it is by the browser agent (from android).

**Comment by ftde0** [comment]
a well configured yt2009 instance along with a good patch do work on older android versions. that was also taken into consideration when working on mobile app support.

consider setting ALL urls you change to HTTP, or use a proxy to see whether the requests are made correctly.

following screenshots are from android 2.3.5.
![ax86](https://github.com/ftde0/yt2009/assets/76792259/145a5942-0924-4d78-898d-1308e671ffe5)
![ax86-vpl](https://github.com/ftde0/yt2009/assets/76792259/87df9f83-8df9-4f34-9782-9e1f5f7c8d4a)

**Comment by mrkrabs206** [comment]
Thanks for the tip!
