### ISSUE TITLE
(serious suggestion) YT2009 needs to be updated to support 1.x YouTube apps (excluding beta).

### ISSUE THREAD

**Issue by mrkrabs206** [ftde0/yt2009#74]
Alright, this is a serious suggestion.

So, you know, any YT2009 instance (port 80 only) supports app patching (from 2.x to 4.x). But, 1.x is also supported (although not for now). I was curious to try 1.x (to go back to early 2010, tried 1.6.21 which supports android 2.2 and later). It didn't crash, but it didn't connect to YT2009. It just said **[Attention] There was a problem starting up. Please check network connections, and check that the system time is set correctly.** So, it seems like it isn't compatible with earlier versions of YouTube (at least for now).

But, in `apk-setup.md`, it shows that earlier versions need a lot more work to get it running.

Here is apk I have tried: https://www.mediafire.com/file/70b5aw873hym4ax/1.6.21.apk/file

Here is proof (1.6.21 and 2.4.4 differences):

![Screenshot_2024 04 10_22 29 48 430](https://github.com/ftde0/yt2009/assets/110676833/3421f96a-3112-4b04-ba68-f58cc3221e7b)
Homepage on 1.6.21 (non work)

![Screenshot_2024 04 10_21 38 17 339](https://github.com/ftde0/yt2009/assets/110676833/34a6a549-fa4c-4282-be92-f745cbbe7343)
Homepage on 2.4.4

![Screenshot_2024 04 10_21 49 38 190](https://github.com/ftde0/yt2009/assets/110676833/4fec759d-8137-4ec7-9acc-4b5417af482f)
Search page on 1.6.21 (non work)

![Screenshot_2024 04 10_21 38 25 289](https://github.com/ftde0/yt2009/assets/110676833/6f53f835-5806-4e7c-b0a2-dca5ab37df4a)
Search page on 2.4.4

We need an update for this so we can now support 1.x apps and we can patch them anytime.

**Comment by ftde0** [comment]
1.x compatibility can require some code modification. i'll have a look in the near future if something can be done to satisfy both 1.x users and others.

**Comment by mrkrabs206** [comment]
> 1.x compatibility can require some code modification. i'll have a look in the near future if something can be done to satisfy both 1.x users and others.

Sounds good
