### ISSUE TITLE
Auto maintain issues?

### ISSUE THREAD

**Issue by FurblandChannel** [ftde0/yt2009#76]
What measurement does the auto maintain use? Should it be just a number and if so is that number MB or GB or something else? Am I supposed to specify the unit for it to measure in? I couldn’t find anything on this in the documentation.

**Comment by ftde0** [comment]
as described in https://github.com/ftde0/yt2009/blob/main/docker.md,
`auto_maintain` is a toggle switch which accepts true/false.
to set the target size, use `maintain_max_size` which is a **number** of target **GB**.

please account for the fact that auto_maintain purges every once in a while, so if you're heavily using yt2009 before the purge comes up the instance may exceed its size. so consider setting the **GB** value a little lower so a purge is more likely to happen, especially if you're working with low disk space.

**Comment by FurblandChannel** [comment]
Got it, it wasn’t specified in the arguments list and I didn’t think to look in the Docker config documentation. Thanks!
