### ISSUE TITLE
(Updates) Status on YT2009 compatibility with 1.x YouTube APKs

### ISSUE THREAD

**Issue by mrkrabs206** [ftde0/yt2009#77]
Here, this is an open updates page for status.

Since I'm tired of waiting (and probably you), I have decided to make this for everyone.

Hopefully we can make 1.x apps supported with YT2009 in the near future someday (ftde0 said).

Last week: no response

Stay tuned for updates!

**Comment by ftde0** [comment]
i did release an update 3 days ago that addresses some of 1.x issues.
https://github.com/ftde0/yt2009/commit/f955cc7d4369a3ad5d46b27044d36b455b442fc2

if you're still experiencing issues with 1.6.21, make sure you've set `shouldUseMasf` to `false`.
you can find where `shouldUseMasf` is by opening a 1.6.20(E) APK in [jadx](https://github.com/skylot/jadx/releases) as this one doesn't have obfuscated variable names, unlike 1.6.21. apply the required change for your 1.6.21 decompile.

**Comment by mrkrabs206** [comment]
> i did release an update 3 days ago that addresses some of 1.x issues. [f955cc7](https://github.com/ftde0/yt2009/commit/f955cc7d4369a3ad5d46b27044d36b455b442fc2)
> 
> if you're still experiencing issues with 1.6.21, make sure you've set `shouldUseMasf` to `false`. you can find where `shouldUseMasf` is by opening a 1.6.20(E) APK in [jadx](https://github.com/skylot/jadx/releases) as this one doesn't have obfuscated variable names, unlike 1.6.21. apply the required change for your 1.6.21 decompile.

Okk

**Comment by mrkrabs206** [comment]
> i did release an update 3 days ago that addresses some of 1.x issues. [f955cc7](https://github.com/ftde0/yt2009/commit/f955cc7d4369a3ad5d46b27044d36b455b442fc2)
> 
> if you're still experiencing issues with 1.6.21, make sure you've set `shouldUseMasf` to `false`. you can find where `shouldUseMasf` is by opening a 1.6.20(E) APK in [jadx](https://github.com/skylot/jadx/releases) as this one doesn't have obfuscated variable names, unlike 1.6.21. apply the required change for your 1.6.21 decompile.

There isn't a shouldusemasf in 1.6.21

**Comment by ftde0** [comment]
yes, as variable and class names in 1.6.21 are obfuscated. i referenced 1.6.20(E) as its variable and class names aren't obfuscated (and have a `shouldUseMasf` but the versions themselves don't work on modern android). once you find where `shouldUseMasf` would be in 1.6.21 (using 1.6.20(E)) you can set it to false.

**Comment by mrkrabs206** [comment]
> yes, as variable and class names in 1.6.21 are obfuscated. i referenced 1.6.20(E) as its variable and class names aren't obfuscated (and have a `shouldUseMasf` but the versions themselves don't work on modern android). once you find where `shouldUseMasf` would be in 1.6.21 (using 1.6.20(E)) you can set it to false.

Is there any other way to edit it? My friend wants to patch it and is his first time patching 1.6.21. He did try 1.6.20 and there were shouldUseMasf there but not 1.6.21. Weird.

**Comment by mrkrabs206** [comment]
> yes, as variable and class names in 1.6.21 are obfuscated. i referenced 1.6.20(E) as its variable and class names aren't obfuscated (and have a `shouldUseMasf` but the versions themselves don't work on modern android). once you find where `shouldUseMasf` would be in 1.6.21 (using 1.6.20(E)) you can set it to false.

thank you

**Comment by mrkrabs206** [comment]
@ftde0 https://github.com/ftde0/yt2009/issues/78
