### ISSUE TITLE
Now we just need to make a tutorial patching earlier versions of YouTube with new update (almost there).

### ISSUE THREAD

**Issue by mrkrabs206** [ftde0/yt2009#78]
After new update released on gdata minor fixes, we just need a tutorial for patching 1.6.21 and below YouTube apps.

I know this sounds crazy, but this is necessary to complete the 1.x app patching.

Be prepared, as this will be called **earlyapk_setup.md**.

here for update: https://github.com/ftde0/yt2009/commit/f955cc7d4369a3ad5d46b27044d36b455b442fc2

Stay tuned!

**Comment by ftde0** [comment]
staying tuned!

**Comment by mrkrabs206** [comment]
> staying tuned!

Thank you!!!! I LOVE YOUR YT2009!

**Comment by mrkrabs206** [comment]
@ftde0 Hopefully you may go work on the tutorial (earlyapk_setup.md). Staying tuned!

**Comment by mrkrabs206** [comment]
> You could always start work on it yourself and then make a pull request!

Idk how

**Comment by FurblandChannel** [comment]
Fork the repo, add the guide, and then make a pull request. If you’re still confused, Google it.
