### ISSUE TITLE
Good news: YT2009 will now support HQ/HD videos (all videos) on all YouTube apps (1.x-4.x)

### ISSUE THREAD

**Issue by mrkrabs206** [ftde0/yt2009#79]
For some reason, one video supports the HD (720p) capabilities. And it was **"Ice Cube - It Was A Good Day** by IceCubeVEVO (with VEVO logo when video plays only on 2.x-3.x).

I tested this on 2.4.4, 3.5.5 and 4.3.9, all work with no problems (HD on and off).

Neat feature to be added to all HD (720p+) and HQ (480p) videos in the future one day. SD/LQ (<360p) will be kept AS-IS.

Here's the results on every app and device:

![Screenshot_20240424-123804](https://github.com/ftde0/yt2009/assets/110676833/09c4246a-5b80-4806-a3ad-47f965c7f76f)
Homepage with one HD video (2.4.4)

![Screenshot_20240424-123745](https://github.com/ftde0/yt2009/assets/110676833/12f3b12e-243a-4ed3-9922-95e8ef5b1b48)
Video loading with HD button (HD off, 2.4.4)

![Screenshot_20240424-123940](https://github.com/ftde0/yt2009/assets/110676833/f45d3e95-6bf5-4868-90fe-c698cf108407)
Video with HD button (HD on, 2.4.4)

![Screenshot_20240424-125002](https://github.com/ftde0/yt2009/assets/110676833/dcacf09a-f333-4735-8cae-a18215d1b681)
Homepage with one HD video (3.5.5)

![Screenshot_20240424-125008](https://github.com/ftde0/yt2009/assets/110676833/06192386-0773-4d2c-b9d3-ad460fd1f224)
Video with HD button (HD off, 3.5.5)

![Screenshot_20240424-125021](https://github.com/ftde0/yt2009/assets/110676833/31582dd7-b26b-47ad-ae78-f81f7cf5e35e)
Video with HD button (HD on, 3.5.5)

2.4.4 and 3.5.5 with HD feature was tested correctly on Sony Xperia 10 IV (XQ-CC54) with Android 14 (latest update 65.2.A.2.137).

![Screenshot_2024 04 24_12 54 53 889](https://github.com/ftde0/yt2009/assets/110676833/7cd1c192-7064-4e5e-8ca6-a3096e354674)
Video with HD button (HD off, 4.3.9)

![Screenshot_2024 04 24_12 57 57 720](https://github.com/ftde0/yt2009/assets/110676833/3a45c10f-4058-4bd0-bb4e-bfaa94cae7dc)
Video with HD button (HD on, 4.3.9)

4.3.9 with HD feature was tested correctly on BlueStacks 5 (5.20.101.1002, App Player 3, Android 11).

Hopefully you could start working on this and more HD/HQ videos will appear soon in home, browse, search, channels, playlists and more (without disappearing when leaving the app). @ftde0 

Also @ftde0, when would you work on earlyapk_setup.md, I'm so excited to see it (I'm starting to be bored with 2.x, 3.x and 4.x apps).
No, this isn't spamming or begging, this is just an information on earlyapk_setup.md.

Get ready for HQ/HD videos because now we can watch videos way more clearer than the boring old 360p (LQ/SD).

**Comment by breakgimme** [comment]
> Also @ftde0, when would you work on earlyapk_setup.md, I'm so excited to see it (I'm starting to be bored with 2.x, 3.x and 4.x apps).

why are you tagging him? there's no pull request with the tutorial you announced you would make in #78

**Comment by ftde0** [comment]
because of how those apps work, full HD across all videos is unlikely.

precisely, those apps need to know the available qualities BEFORE you click on them. finding out qualities of a video in most cases requires an additional request to youtube, which would result in around 20 video requests per feed (search, related, channel videos, playlists etc), which would not only be horrible for performance but also for - well - just the fact that you're doing 20 requests at once, which could pretty quickly make up a ratelimit/ban.

videos in homepage feeds already have cached data in most cases (and as such - available qualities) so they can have HD/HQ formats sent.

**Comment by mrkrabs206** [comment]
> > Also @ftde0, when would you work on earlyapk_setup.md, I'm so excited to see it (I'm starting to be bored with 2.x, 3.x and 4.x apps).
> 
> why are you tagging him? there's no pull request with the tutorial you announced you would make in #78

How to get a pull request?

**Comment by mrkrabs206** [comment]
> > Also @ftde0, when would you work on earlyapk_setup.md, I'm so excited to see it (I'm starting to be bored with 2.x, 3.x and 4.x apps).
> 
> why are you tagging him? there's no pull request with the tutorial you announced you would make in #78

How do I open a pull request, It won't let me create one
