### ISSUE TITLE
Android APK is not working

### ISSUE THREAD

**Issue by bruhsoundfx** [ftde0/yt2009#8]
![image](https://github.com/ftde0/yt2009/assets/143531875/238d0642-457d-4b0e-a295-b2f22a438dff)
Hello. I setup the APK and it showed me this error. Did i do something wrong?

**Comment by ftde0** [comment]
> Did i do something wrong?

most likely. the error on the picture shows up when the device registration step has failed. make sure you've put the ip in right and that your device can access it, also make sure you've changed the aes method padding like mentioned in the guide.

if stuck, in some cases you can set up a proxy between a pc and your android device which. it is harder to get it fully working but easier to tell what's wrong afterwards.

**Comment by lovebug0706** [comment]
This happens to me too. I tried Youtube 2.1.6.

**Comment by ftde0** [comment]
> > Did i do something wrong?
> 
> most likely. the error on the picture shows up when the device registration step has failed. make sure you've put the ip in right and that your device can access it, also make sure you've changed the aes method padding like mentioned in the guide.
> 
> if stuck, in some cases you can set up a proxy between a pc and your android device which. it is harder to get it fully working but easier to tell what's wrong afterwards.

no reply for a bit of time from the original poster, if still needed reopen/make a new issue.
