### ISSUE TITLE
Captions support on youtube mobile apps?

### ISSUE THREAD

**Issue by mrkrabs206** [ftde0/yt2009#80]
As of now, only the web version of YT2009 allows captions on most videos with captions.

But, there is only one that captions weren't implemented on YT2009, and that's the mobile apps.
Like, why this isn't supported yet on these (1.x-4.x)?

I found them in the files and I want to show you some of these.

1.x:

![ic_menu_captions](https://github.com/ftde0/yt2009/assets/110676833/aed633b6-92bb-4bb2-be73-da81d1c39add)
Captions button
![btn_cc_off](https://github.com/ftde0/yt2009/assets/110676833/663a9556-c981-4920-9738-2164a3278a9c)
Captions off
![btn_cc_on](https://github.com/ftde0/yt2009/assets/110676833/8027c536-e181-4c58-b47b-7bab170bafb9)
Captions on

2.x:
![btn_cc_off](https://github.com/ftde0/yt2009/assets/110676833/93888e03-815d-4ff3-b426-9a50d4b202be)
Captions off
![btn_cc_off_focus](https://github.com/ftde0/yt2009/assets/110676833/536c3a73-e901-487e-8748-15f124c4b380)
Captions off (pressed)
![btn_cc_on](https://github.com/ftde0/yt2009/assets/110676833/624c6f97-2d1e-4e64-a53f-235fec475c89)
Captions on
![btn_cc_on_focus](https://github.com/ftde0/yt2009/assets/110676833/73063f1f-521e-478f-8fff-823e98974557)
Captions on (pressed)

3.x:
![ic_vidcontrol_cc_off](https://github.com/ftde0/yt2009/assets/110676833/4ae4e818-1230-4bd9-a4ad-811f8049779f)
Captions off
![ic_vidcontrol_cc_on](https://github.com/ftde0/yt2009/assets/110676833/2e9df261-2c0a-45b8-af51-aae5a0135fdc)
Captions on

4.x:
![ic_vidcontrol_cc_off](https://github.com/ftde0/yt2009/assets/110676833/5241aa21-1e4a-4398-8761-0a7478aa9d0b)
Captions off
![ic_vidcontrol_cc_on](https://github.com/ftde0/yt2009/assets/110676833/084db931-1477-42a5-a6aa-5c4f68a45fe5)
Captions on

It could be great to add this feature to mobile apps to understand the video for deaf people and the people who speak in another language (French, Spanish etc).

This is my last idea to be shared.

Hopefully this will be done.

**Comment by mrkrabs206** [comment]
Please @ftde0 it is easy to get captions on mobile too

**Comment by breakgimme** [comment]
Pull requests are welcome if it's so easy!

**Comment by mrkrabs206** [comment]
> Pull requests are welcome if it's so easy!

It needs a comparison of the two so it not let me

**Comment by breakgimme** [comment]
yeah, that's how pull requests work, you compare the upstream code to your code that has the mobile captions implementation

**Comment by gigigigi53** [comment]
Any updates? It's been 5 months...

**Comment by ftde0** [comment]
i've mentioned this already to you in a different issue.
captions would need additional requests which would drastically slow down loading times and the amount of requests made to youtube, which already is quite big.

**Comment by gigigigi53** [comment]
> i've mentioned this already to you in a different issue. captions would need additional requests which would drastically slow down loading times and the amount of requests made to youtube, which already is quite big.

Maybe in the future it's possible on mobile

**Comment by gigigigi53** [comment]
and read issue #128 @ftde0
