### ISSUE TITLE
yt2009.sliplane.app stopped working on older Android.

### ISSUE THREAD

**Issue by mrkrabs206** [ftde0/yt2009#82]
So last month, YouTube (2.1.6) with yt2009.sliplane.app did work perfectly fine on Android 4.4.4.

But now, any version stopped working with it.

It can't even register my device anymore.
![Screenshot_2024-04-30-15-31-38](https://github.com/ftde0/yt2009/assets/110676833/1562d699-df6d-465d-86c8-660eb4583d9b)

But what's even worse is that the site doesn't even load correctly in the browser.
And when trying to load a video, it will crash the browser.

On chrome, it will load ok, but videos don't even load.
![Screenshot_2024-04-21-19-49-31](https://github.com/ftde0/yt2009/assets/110676833/a348cd7e-8c8d-4304-9831-7f0c73416a2a)

It has http and old html support, but it's not the case on older Android.

How can I resolve this? Ps it's not my yt2009.

**Comment by breakgimme** [comment]
report this to whoever runs that instance, this doesn't belong here

**Comment by FurblandChannel** [comment]
> > report this to whoever runs that instance, this doesn't belong here
> 
> Ok

Instance admin here. No idea what could be causing that, my best guess is you need to update your device's certs (or the app is using an unsupported HTTPS protocol)

**Comment by mrkrabs206** [comment]
> > > report this to whoever runs that instance, this doesn't belong here
> > 
> > 
> > Ok
> 
> Instance admin here. No idea what could be causing that, my best guess is you need to update your device's certs (or the app is using an unsupported HTTPS protocol)

Alas hardware capabilities
