### ISSUE TITLE
Avatars and yt2009 crashes

### ISSUE THREAD

**Issue by VictorFilimonov** [ftde0/yt2009#85]
Replace yt3.ggpht.com with yt3.googleusercontent.com please, when fetch avatars

**Comment by ftde0** [comment]
fix in https://github.com/ftde0/yt2009/commit/49869cd1a11f581a8a6be358a15766d53805860a.

**Comment by VictorFilimonov** [comment]
@ftde0, thank you

**Comment by VictorFilimonov** [comment]
Khm... Same errors...
`$ node backend.js

    ==========

    yt2009 - dev

    ==========
    launch time: 21:48

received 25 videos from master
added 50 comments from master
() aVosoQA9_i8 clean fetch 1715280539632
[dev] using comments_viewmodel_parser instead
[dev] using comments_viewmodel_parser instead

C:\yt2009\node_modules\node-fetch\lib\index.js:1501
                        reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
                               ^
FetchError: request to https://yt3.ggpht.com/ytc/AIdro_nTSmBurrBHUOrlclm3Vf8II4yTvdBJm8DiPFM7oWT_Nuo=s88-c-k-c0x00ffffff-no-rj failed, reason: connect ETIMEDOUT 91.219.75.1
24:443
    at ClientRequest.<anonymous> (C:\yt2009\node_modules\node-fetch\lib\index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}

Node.js v20.11.1
`

**Comment by ftde0** [comment]
are you sure you're up to date? navigate to `/ver` on your yt2009 instance to show the version. `1.13.0.2` is the one with the yesterday's update. anything lower means you're out of date.

**Comment by VictorFilimonov** [comment]
> are you sure you're up to date? navigate to `/ver` on your yt2009 instance to show the version. `1.13.0.2` is the one with the yesterday's update. anything lower means you're out of date.

Oh, I'm blind.
Updated to the latest version as in Readme.
Thank you
